export const COURSES = [
    {
      "course": "Course Code",
      "semester": "Session Code",
      "title": "Course Title",
      "subtitle": "Subtitle",
      "sessionType": "LEC/PRA/TUT",
      "section": "Section",
      "credit": "Credit",
      "required_course_1": "Required Course",
      "required_course_2": "Required Course",
      "required_course_3": "Required Course",
      "day": "Day 1",
      "time": "Start Time 1",
      "day_2": "Day 2",
      "time_2": "Start Time 2",
      "method": "Delivery Method",
      "instructor": "Instructor",
      "instructor_two": "Instructor",
      "notes": "Notes"
    },
    {
      "course": "BKS1001H",
      "semester": "F",
      "title": "Introduction to Book History",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "BHPC collaborative specialization",
      "day": "Monday",
      "time": "2-5pm",
      "method": "In-Person",
      "instructor": "David Fernandez",
      "notes": "course is reserved for BHPC students but non-BHPC students may be able to take it by permission of the instructor"
    },
    {
      "course": "INF1001H",
      "semester": "F",
      "title": "Knowledge and Information in Society",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "CIPS",
      "required_course_2": "GPO",
      "day": "Monday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Leslie Shade"
    },
    {
      "course": "INF1003H",
      "semester": "F",
      "title": "Information Systems, Services and Design",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "ARM",
      "required_course_2": "KMIM",
      "Column10": "GPO",
      "day": "Tuesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Colin Furness"
    },
    {
      "course": "INF1003H",
      "semester": "F",
      "title": "Information Systems, Services and Design",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "ARM",
      "required_course_2": "KMIM",
      "Column10": "GPO",
      "day": "Tuesday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Luke Russell"
    },
    {
      "course": "INF1240H",
      "semester": "F",
      "title": "Research Methods",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "THESIS",
      "required_course_2": "GPO",
      "day": "Wednesday",
      "time": "2-4pm",
      "method": "In-Person",
      "instructor": "Sara Grimes"
    },
    {
      "course": "INF1321H",
      "semester": "F",
      "title": "Representing, Documenting, and Accessing the Cultural Record ",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "LIS",
      "day": "Tuesday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Eva Jansen"
    },
    {
      "course": "INF1321H",
      "semester": "F",
      "title": "Representing, Documenting, and Accessing the Cultural Record ",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "LIS",
      "day": "Thursday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "eva Jansen"
    },
    {
      "course": "INF1323H",
      "semester": "F",
      "title": "The Information Experience",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "LIS",
      "day": "Wednesday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Jenna Hartel"
    },
    {
      "course": "INF1323H",
      "semester": "F",
      "title": "The Information Experience",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "LIS",
      "day": "Monday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Jenna Hartel"
    },
    {
      "course": "INF1330H",
      "semester": "F",
      "title": "Archives, Concepts and Issues",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "ARM",
      "day": "Monday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Seamus Ross",
      "notes": "need to choose one (1) tutorial section along with the lecture section"
    },
    {
      "course": "INF1330H",
      "semester": "F",
      "title": "Archives, Concepts and Issues",
      "sessionType": "TUT",
      "section": 101,
      "credit": 0,
      "required_course_1": "ARM",
      "day": "Monday",
      "time": "4-5pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF1330H",
      "semester": "F",
      "title": "Archives, Concepts and Issues",
      "sessionType": "TUT",
      "section": 102,
      "credit": 0,
      "required_course_1": "ARM",
      "day": "Monday",
      "time": "5-6pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF1330H",
      "semester": "F",
      "title": "Archives, Concepts and Issues",
      "sessionType": "TUT",
      "section": 103,
      "credit": 0,
      "required_course_1": "ARM",
      "day": "Tuesday",
      "time": "4-5pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF1330H",
      "semester": "F",
      "title": "Archives, Concepts and Issues",
      "sessionType": "TUT",
      "section": 104,
      "credit": 0,
      "required_course_1": "ARM",
      "day": "Tuesday",
      "time": "5-6pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF1339H",
      "semester": "F",
      "title": "Introduction to Computational Thinking",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "ISD",
      "day": "Monday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF1339H",
      "semester": "F",
      "title": "Introduction to Computational Thinking",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "ISD",
      "day": "Wednesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF1340H",
      "semester": "F",
      "title": "Programming for Data Science",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "HCDS",
      "day": "Wednesday",
      "time": "10-1pm",
      "method": "In-Person",
      "instructor": "Maher Elshakankiri"
    },
    {
      "course": "INF1340H",
      "semester": "F",
      "title": "Programming for Data Science",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "HCDS",
      "day": "Tuesday",
      "time": "10-1pm",
      "method": "In-Person",
      "instructor": "Shion Guha"
    },
    {
      "course": "INF1341H",
      "semester": "F",
      "title": "System Analysis and Process Innovation",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "ISD",
      "day": "Monday",
      "time": "10-1pm",
      "method": "In-Person",
      "instructor": "Maher Elshakankiri"
    },
    {
      "course": "INF1341H",
      "semester": "F",
      "title": "System Analysis and Process Innovation",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "ISD",
      "day": "Thursday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Safwat Hassan"
    },
    {
      "course": "INF1344H",
      "semester": "F",
      "title": "Introduction to Statistics for Data Science",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "HCDS",
      "day": "Thursday",
      "time": "2-4pm",
      "method": "Online Synchronous",
      "instructor": "Jia Xue"
    },
    {
      "course": "INF1344H",
      "semester": "F",
      "title": "introduction to Statistics for Data Science",
      "sessionType": "TUT",
      "section": 101,
      "credit": 0,
      "required_course_1": "HCDS",
      "day": "Monday",
      "time": "10-11:00am",
      "method": "In-Person",
      "instructor": "Jia Xue",
      "notes": "this tutorial is for INF1344H lecture 0101"
    },
    {
      "course": "INF1344H",
      "semester": "F",
      "title": "introduction to Statistics for Data Science",
      "sessionType": "TUT",
      "section": 102,
      "credit": 0,
      "required_course_1": "HCDS",
      "day": "Thursday",
      "time": "5-6pm",
      "method": "In-Person",
      "instructor": "Jia Xue",
      "notes": "this tutorial is for INF1344H lecture 0101"
    },
    {
      "course": "INF1344H",
      "semester": "F",
      "title": "introduction to Statistics for Data Science",
      "sessionType": "TUT",
      "section": 103,
      "credit": 0,
      "required_course_1": "HCDS",
      "day": "Friday",
      "time": "10-11:00am",
      "method": "In-Person",
      "instructor": "Jia Xue",
      "notes": "this tutorial is for INF1344H lecture 0101"
    },
    {
      "course": "INF1344H",
      "semester": "F",
      "title": "introduction to Statistics for Data Science",
      "sessionType": "LEC",
      "section": 201,
      "credit": 0.5,
      "required_course_1": "HCDS",
      "day": "Thursday",
      "time": "6:30-8:30pm",
      "method": "In-Person",
      "instructor": "Ali Sher"
    },
    {
      "course": "INF1344H",
      "semester": "F",
      "title": "introduction to Statistics for Data Science",
      "sessionType": "TUT",
      "section": 201,
      "credit": 0,
      "required_course_1": "HCDS",
      "day": "Thursday",
      "time": "2-3pm",
      "method": "In-Person",
      "instructor": "Ali Sher",
      "notes": "this tutorial is for INF1344H lecture 0201"
    },
    {
      "course": "INF1344H",
      "semester": "F",
      "title": "introduction to Statistics for Data Science",
      "sessionType": "TUT",
      "section": 202,
      "credit": 0,
      "required_course_1": "HCDS",
      "day": "Thursday",
      "time": "3-4pm",
      "method": "In-Person",
      "instructor": "Ali Sher",
      "notes": "this tutorial is for INF1344H lecture 0201"
    },
    {
      "course": "INF1501H",
      "semester": "F",
      "title": "Culture &amp; Technology I",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "C&amp;T",
      "day": "Monday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Claire Battershill"
    },
    {
      "course": "INF1602H",
      "semester": "F",
      "title": "Fundamentals of User Experience",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "UXD",
      "day": "Monday",
      "time": "5-8pm",
      "day_2": "Thursday",
      "time_2": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Velian Pandeliev",
      "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
    },
    {
      "course": "INF1602H",
      "semester": "F",
      "title": "Fundamentals of User Experience",
      "sessionType": "PRA",
      "section": 101,
      "credit": 0,
      "required_course_1": "UXD",
      "day": "Tuesday",
      "time": "9-11:00am",
      "method": "In-Person",
      "instructor": "Velian Pandeliev",
      "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
    },
    {
      "course": "INF1602H",
      "semester": "F",
      "title": "Fundamentals of User Experience",
      "sessionType": "PRA",
      "section": 102,
      "credit": 0,
      "required_course_1": "UXD",
      "day": "Tuesday",
      "time": "11-1pm",
      "method": "In-Person",
      "instructor": "Velian Pandeliev",
      "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
    },
    {
      "course": "INF1602H",
      "semester": "F",
      "title": "Fundamentals of User Experience",
      "sessionType": "PRA",
      "section": 103,
      "credit": 0,
      "required_course_1": "UXD",
      "day": "Wednesday",
      "time": "12-2pm",
      "method": "In-Person",
      "instructor": "Velian Pandeliev",
      "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
    },
    {
      "course": "INF1602H",
      "semester": "F",
      "title": "Fundamentals of User Experience",
      "sessionType": "PRA",
      "section": 104,
      "credit": 0,
      "required_course_1": "UXD",
      "day": "Wednesday",
      "time": "2-4pm",
      "method": "In-Person",
      "instructor": "Velian Pandeliev",
      "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
    },
    {
      "course": "INF1602H",
      "semester": "F",
      "title": "Fundamentals of User Experience",
      "sessionType": "PRA",
      "section": 105,
      "credit": 0,
      "required_course_1": "UXD",
      "day": "Thursday",
      "time": "5:30-7:30pm",
      "method": "In-Person",
      "instructor": "Velian Pandeliev",
      "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
    },
    {
      "course": "INF1602H",
      "semester": "F",
      "title": "Fundamentals of User Experience",
      "sessionType": "PRA",
      "section": 106,
      "credit": 0,
      "required_course_1": "UXD",
      "day": "Thursday",
      "time": "7:30-9:30pm",
      "method": "In-Person",
      "instructor": "Velian Pandeliev",
      "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
    },
    {
      "course": "INF2122H",
      "semester": "F",
      "title": "Digital Preservation and Curation",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Tuesday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Stephen Marks"
    },
    {
      "course": "INF2122H",
      "semester": "F",
      "title": "Digital Preservation and Curation",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "day": "Thursday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Stephen Marks"
    },
    {
      "course": "INF2124H",
      "semester": "F",
      "title": "Surveillance and Identity",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Wednesday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Kenzie Burchell"
    },
    {
      "course": "INF2149H",
      "semester": "F",
      "title": "Administrative Decision-Making in Information Organizations",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Friday",
      "time": "1-4pm",
      "method": "Online Synchronous",
      "instructor": "Chun Wei Choo"
    },
    {
      "course": "INF2155H",
      "semester": "F",
      "title": "The Public Library in the Community: Developing a Critical Practice",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Thursday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Siobhan Stevenson"
    },
    {
      "course": "INF2162H",
      "semester": "F",
      "title": "Rare Books and Manuscripts",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Wednesday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Timothy Perry",
      "notes": "2nd+ year students only"
    },
    {
      "course": "INF2165H",
      "semester": "F",
      "title": "Accessibility and Inclusive Design",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Thursday",
      "time": "11-2pm",
      "method": "In-Person",
      "instructor": "Priyank Chandra"
    },
    {
      "course": "INF2170H",
      "semester": "F",
      "title": "Information Architecture",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "UXD",
      "day": "Monday",
      "time": "2-5pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF2170H",
      "semester": "F",
      "title": "Information Architecture",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "UXD",
      "day": "Tuesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF2173H",
      "semester": "F",
      "title": "Information Professional Practicum ",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Friday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "TBD",
      "notes": "2nd+ year MI students only"
    },
    {
      "course": "INF2273H",
      "semester": "F",
      "title": "Information Professional Practicum II",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Friday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "TBD",
      "notes": "2nd+ year MI students only who have completed INF2173H"
    },
    {
      "course": "INF2175H",
      "semester": "F",
      "title": "Managing Organizational Records I",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "ARM",
      "required_course_2": "KMIM",
      "day": "Monday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Tys Klumpenhouwer"
    },
    {
      "course": "INF2176H",
      "semester": "F",
      "title": "Information Management in Organizations-Models and Platforms",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "KMIM",
      "day": "Monday",
      "time": "1-4pm",
      "method": "Online Synchronous",
      "instructor": "Chun Wei Choo"
    },
    {
      "course": "INF2180H",
      "semester": "F",
      "title": "Archives, Access, Advocacy and Outreach",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Wednesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "TBD"
    },
    {
      "course": "INF2190H",
      "semester": "F",
      "title": "Data Analytics: Introduction, Methods and Practical Approaches",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "HCDS",
      "day": "Tuesday",
      "time": "2-5pm",
      "method": "In-Person",
      "instructor": "Tegan Maharaj"
    },
    {
      "course": "INF2190H",
      "semester": "F",
      "title": "Data Analytics: Introduction, Methods and Practical Approaches",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "HCDS",
      "day": "Wednesday",
      "time": "2-5pm",
      "method": "In-Person",
      "instructor": "Tegan Maharaj"
    },
    {
      "course": "INF2200H",
      "semester": "F",
      "title": "UX Leadership and Influence",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Tuesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Alison Cox",
      "instructor_two": "Gord Davison"
    },
    {
      "course": "INF2201H",
      "semester": "F",
      "title": "Information and Communication Technologies, Design, and Marginality",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Wednesday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Priyank Chandra"
    },
    {
      "course": "INF2208H",
      "semester": "F",
      "title": "User-Centered Systems for Communication",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Thursday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Anastasia Kuzminykh"
    },
    {
      "course": "INF2209H",
      "semester": "F",
      "title": "Human-Centred Topic Models",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Tuesday",
      "time": "2-5pm",
      "method": "In-Person",
      "instructor": "Shion Guha"
    },
    {
      "course": "INF2227H",
      "semester": "F",
      "title": "Asset-based and Community-led Development (ABCD) for the GLAM Sector",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Friday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Siobhan Stevenson",
      "notes": "2nd+ year students who have completed their required courses for their concentration"
    },
    {
      "course": "INF2230H",
      "semester": "F",
      "title": "Just Sustainability Design",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Wednesday",
      "time": "1-4pm",
      "method": "Online Synchronous",
      "instructor": "Christoph Becker",
      "notes": "2nd+ year students only"
    },
    {
      "course": "INF2240H",
      "semester": "F",
      "title": "Political Economy and Cultural Studies of Information",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "CIPS",
      "day": "Friday",
      "time": "10-1pm",
      "method": "In-Person",
      "instructor": "Nicole Cohen"
    },
    {
      "course": "INF2241H",
      "semester": "F",
      "title": "Critical Making: Information Studies, Social Values, and Physical Computing",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "C&amp;T",
      "day": "Tuesday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Matt Ratto"
    },
    {
      "course": "INF2314H",
      "semester": "F",
      "title": "Program Evaluation",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Monday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Kim Silk"
    },
    {
      "course": "INF2319H",
      "semester": "F",
      "title": "Critical Approaches to Multiculturalism, Information, and Social Integration",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Thursday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Sherry Yu"
    },
    {
      "course": "INF2332H",
      "semester": "F",
      "title": "Information Behaviour",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Monday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Brian Griffin"
    },
    {
      "course": "INF2401H",
      "semester": "F",
      "title": "Special Topics in Information ",
      "subtitle": "Coded Culture: The Rise of Digital Media Platforms",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Tuesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Matthew Wells"
    },
    {
      "course": "INF2404H",
      "semester": "F",
      "title": "Special Topics in Information",
      "subtitle": "Explainability &amp; Fairness for Responsible Machine Learning",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Friday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Vik Pant"
    },
    {
      "course": "INF3001H",
      "semester": "F",
      "title": "Research in Information - Foundations",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Friday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Patrick Keilty",
      "notes": "PhD students only"
    },
    {
      "course": "INF3009H",
      "semester": "F",
      "title": "Theory and History of Media Technology",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Wednesday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Jeremy Packer",
      "notes": "PhD students only"
    },
    {
      "course": "INF3102H",
      "semester": "F",
      "title": "Ethics of AI",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Tuesday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Brian Cantwell Smith",
      "notes": "PhD students only"
    },
    {
      "course": "INF3900H",
      "semester": "F",
      "title": "The Emerging Professional",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "Co-op",
      "day": "Wednesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Colin Furness",
      "notes": "MI students only"
    },
    {
      "course": "INF3900H",
      "semester": "F",
      "title": "The Emerging Professional",
      "sessionType": "LEC",
      "section": 102,
      "credit": 0.5,
      "required_course_1": "Co-op",
      "day": "Friday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Colin Furness",
      "notes": "MI students only"
    },
    {
      "course": "INF3903H",
      "semester": "F",
      "title": "Workplace Placement",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "Co-op",
      "day": "No",
      "time": "Meeting ",
      "Column13": "Times",
      "method": "Online Asynchronous",
      "instructor": "Chioma Ekpo",
      "notes": "MI students only, the course does not meet on any specific days and times"
    },
    {
      "course": "KMD1001H",
      "semester": "F",
      "title": "Theory and Methods in Knowledge Media Design",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "KMD collaborative specialization",
      "day": "Monday",
      "time": "4-6pm",
      "method": "In-Person",
      "instructor": "MaryElizabeth Luka",
      "notes": "KMD CS students have priority"
    },
    {
      "course": "MSL2000H",
      "semester": "F",
      "title": "Curatorial Practice",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Monday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Laura Phillips"
    },
    {
      "course": "MSL2115H",
      "semester": "F",
      "title": "Global Cultures and Museums",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Tuesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Bruno Veras"
    },
    {
      "course": "MSL2330H",
      "semester": "F",
      "title": "Interpretation and Meaning-Making in Cultural Institutions",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Thursday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Judith Koke",
      "instructor_two": "Jennifer Orpana"
    },
    {
      "course": "MSL2331H",
      "semester": "F",
      "title": "The Museum Exhibition: Histories, Practices, Genres",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "MMSt",
      "day": "Monday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Irina Mihalache",
      "notes": "must also choose a tutorial section"
    },
    {
      "course": "MSL2331H",
      "semester": "F",
      "title": "The Museum Exhibition: Histories, Practices, Genres",
      "sessionType": "TUT",
      "section": 101,
      "credit": 0,
      "required_course_1": "MMSt",
      "day": "Monday",
      "time": "9-10:30am",
      "method": "In-Person",
      "instructor": "Irina Mihalache"
    },
    {
      "course": "MSL2331H",
      "semester": "F",
      "title": "The Museum Exhibition: Histories, Practices, Genres",
      "sessionType": "TUT",
      "section": 101,
      "credit": 0,
      "required_course_1": "MMSt",
      "day": "Monday",
      "time": "10:30am",
      "Column13": "12pm",
      "method": "In-Person",
      "instructor": "Irina Mihalache"
    },
    {
      "course": "MSL2332H",
      "semester": "F",
      "title": "Public Programs and Education",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Friday",
      "time": "1-4pm",
      "method": "In-Person",
      "instructor": "Hooley McLaughlin"
    },
    {
      "course": "MSL2350H",
      "semester": "F",
      "title": "Museum Planning and Management: Projects and Fundraising",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "MMSt",
      "day": "Thursday",
      "time": "2-5pm",
      "method": "In-Person",
      "instructor": "Judith Koke"
    },
    {
      "course": "MSL2352H",
      "semester": "F",
      "title": "Foundations of Visitor Research",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Wednesday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Angie Ong"
    },
    {
      "course": "MSL2360H",
      "semester": "F",
      "title": "Museums and Indigenous Communities: Changing Relations, Changing Practice",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "day": "Wednesday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "Rheanne Chartrand"
    },
    {
      "course": "MSL2370H",
      "semester": "F",
      "title": "Museums and Cultural Heritage: Context and Critical Issues",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "MMSt",
      "day": "Friday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Joanna Papayiannis"
    },
    {
      "course": "MSL3900H",
      "semester": "F",
      "title": "The Emerging Professional",
      "sessionType": "LEC",
      "section": 101,
      "credit": 0.5,
      "required_course_1": "Pre-requisite for MSL3000H",
      "day": "Monday",
      "time": "6:30-9:30pm",
      "method": "In-Person",
      "instructor": "John Summers",
      "notes": "MMSt students only"
    },
    {
      "course": "MSL4000Y",
      "semester": "Y",
      "title": "Museum Studies Capstone Projects",
      "sessionType": "LEC",
      "section": 101,
      "credit": 1,
      "required_course_1": "MMSt",
      "day": "Thursday",
      "time": "9-12pm",
      "method": "In-Person",
      "instructor": "Cara Krmpotich",
      "instructor_two": "Morgan Mavis",
      "notes": "2nd+ year MMSt students only"
    }

  ]