export const COURSES = [
 {
  "course": "Course Code",
  "title": "Course Title",
  "subtitle": "Subtitle",
  "sessionType": "LEC/PRA/TUT",
  "section": "Section",
  "credit": "Credit",
  "required_course_1": "Required Course",
  "required_course_2": "Required Course",
  "required_course_3": "Required Course",
  "day_1": "Day 1",
  "start_time_1": "Start Time 1",
  "end_time_1": "End Time 1",
  "day_2 ": "Day 2",
  "start_time_2": "Start Time 2",
  "end_time_2": "End Time 3",
  "method": "Delivery Method",
  "instructor": "Instructor",
  "instructor_two": "Instructor",
  "notes": "Notes"
 },
 {
  "course": "BKS1001H",
  "title": "Introduction to Book History",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "BHPC collaborative specialization",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "2:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "David Fernandez",
  "instructor_two": null,
  "notes": "course is reserved for BHPC students but non-BHPC students may be able to take it by permission of the instructor"
 },
 {
  "course": "INF1001H",
  "title": "Knowledge and Information in Society",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "CIPS",
  "required_course_2": "GPO",
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Leslie Shade",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1003H",
  "title": "Information Systems, Services and Design",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "ARM",
  "required_course_2": "KMIM",
  "required_course_3": "GPO",
  "day_1": "Tuesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Colin Furness",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1003H",
  "title": "Information Systems, Services and Design",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "ARM",
  "required_course_2": "KMIM",
  "required_course_3": "GPO",
  "day_1": "Tuesday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Luke Russell",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1240H",
  "title": "Research Methods",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "THESIS",
  "required_course_2": "GPO",
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "2:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Sara Grimes",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1321H",
  "title": "Representing, Documenting, and Accessing the Cultural Record ",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "LIS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1321H",
  "title": "Representing, Documenting, and Accessing the Cultural Record ",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "LIS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1323H",
  "title": "The Information Experience",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "LIS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Jenna Hartel",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1323H",
  "title": "The Information Experience",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "LIS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Jenna Hartel",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1330H",
  "title": "Archives, Concepts and Issues",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "ARM",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Seamus Ross",
  "instructor_two": null,
  "notes": "need to choose one (1) tutorial section along with the lecture section"
 },
 {
  "course": "INF1330H",
  "title": "Archives, Concepts and Issues",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 101,
  "credit": 0,
  "required_course_1": "ARM",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "4:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1330H",
  "title": "Archives, Concepts and Issues",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 102,
  "credit": 0,
  "required_course_1": "ARM",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "5:00pm",
  "end_time_1": "6:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1330H",
  "title": "Archives, Concepts and Issues",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 103,
  "credit": 0,
  "required_course_1": "ARM",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "4:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1330H",
  "title": "Archives, Concepts and Issues",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 104,
  "credit": 0,
  "required_course_1": "ARM",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "5:00pm",
  "end_time_1": "6:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1339H",
  "title": "Introduction to Computational Thinking",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "ISD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1339H",
  "title": "Introduction to Computational Thinking",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "ISD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1340H",
  "title": "Programming for Data Science",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "10:00am",
  "end_time_1": "1:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Maher Elshakankiri",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1340H",
  "title": "Programming for Data Science",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "10:00am",
  "end_time_1": "1:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Shion Guha",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1341H",
  "title": "System Analysis and Process Innovation",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "ISD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "10:00am",
  "end_time_1": "1:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Maher Elshakankiri",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1341H",
  "title": "System Analysis and Process Innovation",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "ISD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Safwat Hassan",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1344H",
  "title": "Introduction to Statistics for Data Science",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "2:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Jia Xue",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1344H",
  "title": "introduction to Statistics for Data Science",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 101,
  "credit": 0,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "10:00am",
  "end_time_1": "11:00am",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Jia Xue",
  "instructor_two": null,
  "notes": "this tutorial is for INF1344H lecture 0101"
 },
 {
  "course": "INF1344H",
  "title": "introduction to Statistics for Data Science",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 102,
  "credit": 0,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "5:00pm",
  "end_time_1": "6:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Jia Xue",
  "instructor_two": null,
  "notes": "this tutorial is for INF1344H lecture 0101"
 },
 {
  "course": "INF1344H",
  "title": "introduction to Statistics for Data Science",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 103,
  "credit": 0,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "10:00am",
  "end_time_1": "11:00am",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Jia Xue",
  "instructor_two": null,
  "notes": "this tutorial is for INF1344H lecture 0101"
 },
 {
  "course": "INF1344H",
  "title": "introduction to Statistics for Data Science",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 201,
  "credit": 0.5,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1344H",
  "title": "introduction to Statistics for Data Science",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 201,
  "credit": 0,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "4:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": "this tutorial is for INF1344H lecture 0201"
 },
 {
  "course": "INF1344H",
  "title": "introduction to Statistics for Data Science",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 202,
  "credit": 0,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "5:00pm",
  "end_time_1": "6:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": "this tutorial is for INF1344H lecture 0201"
 },
 {
  "course": "INF1501H",
  "title": "Culture & Technology I",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "C&T",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Claire Battershill",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF1602H",
  "title": "Fundamentals of User Experience",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "5:00pm",
  "end_time_1": "8:00pm",
  "day_2 ": "Thursday",
  "start_time_2": "6:30pm",
  "end_time_2": "9:30pm",
  "method": "In-Person",
  "instructor": "Velian Pandeliev",
  "instructor_two": null,
  "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
 },
 {
  "course": "INF1602H",
  "title": "Fundamentals of User Experience",
  "subtitle": null,
  "sessionType": "PRA",
  "section": 101,
  "credit": 0,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "9:00am",
  "end_time_1": "11:00am",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Velian Pandeliev",
  "instructor_two": null,
  "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
 },
 {
  "course": "INF1602H",
  "title": "Fundamentals of User Experience",
  "subtitle": null,
  "sessionType": "PRA",
  "section": 102,
  "credit": 0,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "11:00am",
  "end_time_1": "1:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Velian Pandeliev",
  "instructor_two": null,
  "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
 },
 {
  "course": "INF1602H",
  "title": "Fundamentals of User Experience",
  "subtitle": null,
  "sessionType": "PRA",
  "section": 103,
  "credit": 0,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "12:00pm",
  "end_time_1": "2:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Velian Pandeliev",
  "instructor_two": null,
  "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
 },
 {
  "course": "INF1602H",
  "title": "Fundamentals of User Experience",
  "subtitle": null,
  "sessionType": "PRA",
  "section": 104,
  "credit": 0,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "2:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Velian Pandeliev",
  "instructor_two": null,
  "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
 },
 {
  "course": "INF1602H",
  "title": "Fundamentals of User Experience",
  "subtitle": null,
  "sessionType": "PRA",
  "section": 105,
  "credit": 0,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "5:30pm",
  "end_time_1": "7:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Velian Pandeliev",
  "instructor_two": null,
  "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
 },
 {
  "course": "INF1602H",
  "title": "Fundamentals of User Experience",
  "subtitle": null,
  "sessionType": "PRA",
  "section": 106,
  "credit": 0,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "7:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Velian Pandeliev",
  "instructor_two": null,
  "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Thursday) for all students for the first 4 weeks for classes from September 12, 2022 to October 5, 2022 and one practical studio component which will meet ONCE per week from October 11, 2022 to December 8, 2022  "
 },
 {
  "course": "INF2122H",
  "title": "Digital Preservation and Curation",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Stephen Marks",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2122H",
  "title": "Digital Preservation and Curation",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Stephen Marks",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2124H",
  "title": "Surveillance and Identity",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Kenzie Burchell",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2125H",
  "title": "Developing a Diversity Mindset for the Information Professions",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2149H",
  "title": "Administrative Decision-Making in Information Organizations",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "Online Synchronous",
  "instructor": "Chun Wei Choo",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2155H",
  "title": "The Public Library in the Community: Developing a Critical Practice",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Siobhan Stevenson",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2162H",
  "title": "Rare Books and Manuscripts",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Timothy Perry",
  "instructor_two": null,
  "notes": "2nd year MI students only"
 },
 {
  "course": "INF2165H",
  "title": "Accessibility and Inclusive Design",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "11:00am",
  "end_time_1": "2:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Priyank Chandra",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2170H",
  "title": "Information Architecture",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "2:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2170H",
  "title": "Information Architecture",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "UXD",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2173H",
  "title": "Information Professional Practicum",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": "2nd+ year students only"
 },
 {
  "course": "INF2175H",
  "title": "Managing Organizational Records I",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "ARM",
  "required_course_2": "KMIM",
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Tys Klumpenhouwer",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2176H",
  "title": "Information Management in Organizations-Models and Platforms",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "KMIM",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "Online Synchronous",
  "instructor": "Chun Wei Choo",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2180H",
  "title": "Archives, Access, Advocacy and Outreach",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2190H",
  "title": "Data Analytics: Introduction, Methods and Practical Approaches",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "2:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Tegan Maharaj",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2190H",
  "title": "Data Analytics: Introduction, Methods and Practical Approaches",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "HCDS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "2:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Tegan Maharaj",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2200H",
  "title": "UX Leadership and Influence",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Alison Cox",
  "instructor_two": "Gord Davison",
  "notes": null
 },
 {
  "course": "INF2201H",
  "title": "Information and Communication Technologies, Design, and Marginality",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Priyank Chandra",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2208H",
  "title": "User-Centered Systems for Communication",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Anastasia Kuzminykh",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2209H",
  "title": "Human-Centred Topic Models",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "2:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Shion Guha",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2227H",
  "title": "Asset-based and Community-led Development (ABCD) for the GLAM Sector",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Siobhan Stevenson",
  "instructor_two": null,
  "notes": "2nd+ year student who have completed their required courses for their concentration"
 },
 {
  "course": "INF2230H",
  "title": "Just Sustainability Design",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "Online Synchronous",
  "instructor": "Christoph Becker",
  "instructor_two": null,
  "notes": "2nd+ year students only"
 },
 {
  "course": "INF2240H",
  "title": "Political Economy and Cultural Studies of Information",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "CIPS",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "10:00am",
  "end_time_1": "1:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Nicole Cohen",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2241H",
  "title": "Critical Making: Information Studies, Social Values, and Physical Computing",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "C&T",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Matt Ratto",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2314H",
  "title": "Program Evaluation",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Kim Silk",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2319H",
  "title": "Critical Approaches to Multiculturalism, Information, and Social Integration",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Sherry Yu",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2401H",
  "title": "Special Topics in Information ",
  "subtitle": "Coded Culture: The Rise of Digital Media Platforms",
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Matthew Wells",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF2404H",
  "title": "Special Topics in Information",
  "subtitle": "Explainability & Fairness for Responsible Machine Learning",
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Vik Pant",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "INF3001H",
  "title": "Research in Information - Foundations",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Patrick Keilty",
  "instructor_two": null,
  "notes": "PhD students only"
 },
 {
  "course": "INF3009H",
  "title": "Theory and History of Media Technology",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Jeremy Packer",
  "instructor_two": null,
  "notes": "PhD students only"
 },
 {
  "course": "INF3102H",
  "title": "Ethics of AI",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Brian Cantwell Smith",
  "instructor_two": null,
  "notes": "PhD students only"
 },
 {
  "course": "INF3900H",
  "title": "The Emerging Professional",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "Co-op",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Colin Furness",
  "instructor_two": null,
  "notes": "MI students only"
 },
 {
  "course": "INF3900H",
  "title": "The Emerging Professional",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 102,
  "credit": 0.5,
  "required_course_1": "Co-op",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Colin Furness",
  "instructor_two": null,
  "notes": "MI students only"
 },
 {
  "course": "INF3903H",
  "title": "Workplace Placement",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "Co-op",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "No",
     "start_time_1": "Meeting ",
  "end_time_1": "Times",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "Online Asynchronous",
  "instructor": "Chioma Ekpo",
  "instructor_two": null,
  "notes": "MI students only, the course does not meet on any specific days and times"
 },
 {
  "course": "KMD1001H",
  "title": "Theory and Methods in Knowledge Media Design",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "KMD collaborative specialization",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "4:00pm",
  "end_time_1": "6:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "MaryElizabeth Luka",
  "instructor_two": null,
  "notes": "KMD CS students have priority"
 },
 {
  "course": "MSL2000H",
  "title": "Curatorial Practice",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Laura Phillips",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL2115H",
  "title": "Global Cultures and Museums",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Tuesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Bruno Veras",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL2330H",
  "title": "Interpretation and Meaning-Making in Cultural Institutions",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Judith Koke",
  "instructor_two": "Jennifer Orpana",
  "notes": null
 },
 {
  "course": "MSL2331H",
  "title": "The Museum Exhibition: Histories, Practices, Genres",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "MMSt",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Irina Mihalache",
  "instructor_two": null,
  "notes": "must also choose a tutorial section"
 },
 {
  "course": "MSL2331H",
  "title": "The Museum Exhibition: Histories, Practices, Genres",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 101,
  "credit": 0,
  "required_course_1": "MMSt",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "9:00am",
  "end_time_1": "10:30am",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Irina Mihalache",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL2331H",
  "title": "The Museum Exhibition: Histories, Practices, Genres",
  "subtitle": null,
  "sessionType": "TUT",
  "section": 101,
  "credit": 0,
  "required_course_1": "MMSt",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "10:30am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Irina Mihalache",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL2332H",
  "title": "Public Programs and Education",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "1:00pm",
  "end_time_1": "4:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Hooley McLaughlin",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL2350H",
  "title": "Museum Planning and Management: Projects and Fundraising",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "MMSt",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "2:00pm",
  "end_time_1": "5:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Judith Koke",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL2352H",
  "title": "Foundations of Visitor Research",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Angie Ong",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL2360H",
  "title": "Museums and Indigenous Communities: Changing Relations, Changing Practice",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": null,
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Wednesday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "TBD",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL2370H",
  "title": "Museums and Cultural Heritage: Context and Critical Issues",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "MMSt",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Friday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Joanna Papayiannis",
  "instructor_two": null,
  "notes": null
 },
 {
  "course": "MSL3900H",
  "title": "The Emerging Professional",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 0.5,
  "required_course_1": "Pre-requisite for MSL3000H",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Monday",
  "start_time_1": "6:30pm",
  "end_time_1": "9:30pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "John Summers",
  "instructor_two": null,
  "notes": "MMSt students only"
 },
 {
  "course": "MSL4000Y",
  "title": "Museum Studies Capstone Projects",
  "subtitle": null,
  "sessionType": "LEC",
  "section": 101,
  "credit": 1,
  "required_course_1": "MMSt",
  "required_course_2": null,
  "required_course_3": null,
  "day_1": "Thursday",
  "start_time_1": "9:00am",
  "end_time_1": "12:00pm",
  "day_2 ": null,
  "start_time_2": null,
  "end_time_2": null,
  "method": "In-Person",
  "instructor": "Cara Krmpotich",
  "instructor_two": "Morgan Mavis",
  "notes": "2nd+ year MMSt students only"
 }

]