export default
[
    {
        "course": "BKS1001H",
        "title": "Introduction to Book History",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "2-5pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "Course is reserved for BHPC students but non-BHPC students may be able to take it by permission of the instructor",
        "semester": "F"
    },
    {
        "course": "INF1001H",
        "title": "Knowledge and Information in Society",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "10-12pm",
        "method": "Online Sync",
        "instructor": "Leslie Shade",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1001H",
        "title": "Knowledge and Information in Society",
        "sessionType": "TUT",
        "section": "101",
        "day": "Monday",
        "time": "4-5pm",
        "method": "Online Sync",
        "instructor": "Leslie Shade",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1001H",
        "title": "Knowledge and Information in Society",
        "sessionType": "TUT",
        "section": "102",
        "day": "Tuesday",
        "time": "10-11am",
        "method": "In-Person",
        "instructor": "Leslie Shade",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1001H",
        "title": "Knowledge and Information in Society",
        "sessionType": "TUT",
        "section": "103",
        "day": "Tuesday",
        "time": "11-12pm",
        "method": "In-Person",
        "instructor": "Leslie Shade",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1003H",
        "title": "Information Systems, Services and Design",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "1-4pm",
        "method": "Online Sync",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1003H",
        "title": "Information Systems, Services and Design",
        "sessionType": "TUT",
        "section": "104",
        "day": "Saturday",
        "time": "3-4pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1003H",
        "title": "Information Systems, Services and Design",
        "sessionType": "TUT",
        "section": "105",
        "day": "Saturday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1003H",
        "title": "Information Systems, Services and Design",
        "sessionType": "TUT",
        "section": "106",
        "day": "Saturday",
        "time": "5-6pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1003H",
        "title": "Information Systems, Services and Design",
        "sessionType": "TUT",
        "section": "101",
        "day": "Tuesday",
        "time": "6:30-7:30pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1003H",
        "title": "Information Systems, Services and Design",
        "sessionType": "TUT",
        "section": "102",
        "day": "Tuesday",
        "time": "7:30-8:30pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1003H",
        "title": "Information Systems, Services and Design",
        "sessionType": "TUT",
        "section": "103",
        "day": "Tuesday",
        "time": "8:30-9:30pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1230H",
        "title": "Management of Information Organizations",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "6:30-8:30pm",
        "method": "Online Sync",
        "instructor": "Joel Alleyne",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1230H",
        "title": "Management of Information Organizations",
        "sessionType": "TUT",
        "section": "101",
        "day": "Thursday",
        "time": "6:30-7:30pm",
        "method": "In-Person",
        "instructor": "Joel Alleyne",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1230H",
        "title": "Management of Information Organizations",
        "sessionType": "TUT",
        "section": "102",
        "day": "Thursday",
        "time": "7:30-8:30pm",
        "method": "In-Person",
        "instructor": "joel Alleyne",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1230H",
        "title": "Management of Information Organizations",
        "sessionType": "TUT",
        "section": "103",
        "day": "Thursday",
        "time": "8:30-9:30pm",
        "method": "In-Person",
        "instructor": "Joel Alleyne",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1240H",
        "title": "Research Methods",
        "sessionType": "LEC",
        "section": "101",
        "day": "Thursday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1321H",
        "title": "Representing, Documenting, and Accessing the Cultural Record",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "10-12pm",
        "method": "Online Sync",
        "instructor": "Stacy Allison-Cassin",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1321H",
        "title": "Representing, Documenting, and Accessing the Cultural Record",
        "sessionType": "TUT",
        "section": "103",
        "day": "Thursday",
        "time": "2-3pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1321H",
        "title": "Representing, Documenting, and Accessing the Cultural Record",
        "sessionType": "TUT",
        "section": "104",
        "day": "Thursday",
        "time": "3-4pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1321H",
        "title": "Representing, Documenting, and Accessing the Cultural Record",
        "sessionType": "TUT",
        "section": "101",
        "day": "Tuesday",
        "time": "6:30-7:30pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1321H",
        "title": "Representing, Documenting, and Accessing the Cultural Record",
        "sessionType": "TUT",
        "section": "102",
        "day": "Tuesday",
        "time": "7:30-8:30pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1323H",
        "title": "The Information Experience",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "4-6pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1323H",
        "title": "The Information Experience",
        "sessionType": "TUT",
        "section": "103",
        "day": "Friday",
        "time": "10-11am",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1323H",
        "title": "The Information Experience",
        "sessionType": "TUT",
        "section": "104",
        "day": "Friday",
        "time": "11-12pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1323H",
        "title": "The Information Experience",
        "sessionType": "TUT",
        "section": "101",
        "day": "Wednesday",
        "time": "10-11am",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1323H",
        "title": "The Information Experience",
        "sessionType": "TUT",
        "section": "102",
        "day": "Wednesday",
        "time": "11-12pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1330H",
        "title": "Archives, Concepts and Issues",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "9-12pm",
        "method": "Online Sync",
        "instructor": "Seamus Ross",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1330H",
        "title": "Archives, Concepts and Issues",
        "sessionType": "TUT",
        "section": "104",
        "day": "Thursday",
        "time": "5-6pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1330H",
        "title": "Archives, Concepts and Issues",
        "sessionType": "TUT",
        "section": "101",
        "day": "Wednesday",
        "time": "6:30-7:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1330H",
        "title": "Archives, Concepts and Issues",
        "sessionType": "TUT",
        "section": "102",
        "day": "Wednesday",
        "time": "7:30-8:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1330H",
        "title": "Archives, Concepts and Issues",
        "sessionType": "TUT",
        "section": "103",
        "day": "Wednesday",
        "time": "8:30-9:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1339H",
        "title": "Introduction to Computational Thinking",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "1-3pm",
        "method": "Online Sync",
        "instructor": "Dan Ryan",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1339H",
        "title": "Introduction to Computational Thinking",
        "sessionType": "TUT",
        "section": "104",
        "day": "Thursday",
        "time": "6:30-7:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1339H",
        "title": "Introduction to Computational Thinking",
        "sessionType": "TUT",
        "section": "105",
        "day": "Thursday",
        "time": "7:30-8:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1339H",
        "title": "Introduction to Computational Thinking",
        "sessionType": "TUT",
        "section": "106",
        "day": "Thursday",
        "time": "8:30-9:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1339H",
        "title": "Introduction to Computational Thinking",
        "sessionType": "TUT",
        "section": "101",
        "day": "Wednesday",
        "time": "1-2pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1339H",
        "title": "Introduction to Computational Thinking",
        "sessionType": "TUT",
        "section": "102",
        "day": "Wednesday",
        "time": "2-3pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1339H",
        "title": "Introduction to Computational Thinking",
        "sessionType": "TUT",
        "section": "103",
        "day": "Wednesday",
        "time": "3-4pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1340H",
        "title": "Programming for Data Science",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "3-5pm",
        "method": "Online Sync",
        "instructor": "Maher Elshakankiri",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1340H",
        "title": "Programming for Data Science",
        "sessionType": "LEC",
        "section": "202",
        "day": "Wednesday",
        "time": "4-6pm",
        "method": "Online Sync",
        "instructor": "Shion Guha",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1340H",
        "title": "Programming for Data Science",
        "sessionType": "TUT",
        "section": "103",
        "day": "Thursday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for INF1340H lecture 0101",
        "semester": "F"
    },
    {
        "course": "INF1340H",
        "title": "Programming for Data Science",
        "sessionType": "TUT",
        "section": "104",
        "day": "Thursday",
        "time": "5-6pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for INF1340H lecture 0101",
        "semester": "F"
    },
    {
        "course": "INF1340H",
        "title": "Programming for Data Science",
        "sessionType": "TUT",
        "section": "101",
        "day": "Tuesday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for INF1340H lecture 0101",
        "semester": "F"
    },
    {
        "course": "INF1340H",
        "title": "Programming for Data Science",
        "sessionType": "TUT",
        "section": "102",
        "day": "Tuesday",
        "time": "5-6pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for INF1340H lecture 0101",
        "semester": "F"
    },
    {
        "course": "INF1340H",
        "title": "Programming for Data Science",
        "sessionType": "TUT",
        "section": "201",
        "day": "Thursday",
        "time": "6:30-7:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for lecture INF1340H lecture 0202",
        "semester": "F"
    },
    {
        "course": "INF1340H",
        "title": "Programming for Data Science",
        "sessionType": "TUT",
        "section": "202",
        "day": "Thursday",
        "time": "7:30-8:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for lecture INF1340H lecture 0202",
        "semester": "F"
    },
    {
        "course": "INF1341H",
        "title": "System Analysis and Process Innovation",
        "sessionType": "LEC",
        "section": "101",
        "day": "Friday",
        "time": "9-12pm",
        "method": "Online Sync",
        "instructor": "Maher Elshakankiri",
        "instructor_two": "",
        "notes": "this is for ISD concentration students only, take in the fall only",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "drop in",
        "section": "",
        "day": "Monday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "Drop in for INF1344H lecture section 0101 only and not mandatory for lecture section 0101, no need to enrol in ACORN",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "drop in",
        "section": "",
        "day": "Monday",
        "time": "5-6pm",
        "method": "In-Person",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "Drop in for INF1344H lecture section 0101 only and not mandatory for lecture section 0101, no need to enrol in ACORN",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "drop in",
        "section": "",
        "day": "Thursday",
        "time": "12-1pm",
        "method": "In-Person",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "Drop in for INF1344H lecture section 0101 only and not mandatory for lecture section 0101, no need to enrol in ACORN",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "Introduction to Statistics Data Science",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "1-3pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "LEC",
        "section": "202",
        "day": "Wednesday",
        "time": "6:30-8:30pm",
        "method": "Online Sync",
        "instructor": "Abbas Keramti",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "TUT",
        "section": "201",
        "day": "Friday",
        "time": "1-2pm",
        "method": "In-Person",
        "instructor": "Abbas Keramti",
        "instructor_two": "",
        "notes": "this tutorial is for INF1344H lecture 0202",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "TUT",
        "section": "202",
        "day": "Friday",
        "time": "2-3pm",
        "method": "In-Person",
        "instructor": "Abbas Keramti",
        "instructor_two": "",
        "notes": "this tutorial  is for INF1344H lecture 0202",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "TUT",
        "section": "203",
        "day": "Friday",
        "time": "3-4pm",
        "method": "In-Person",
        "instructor": "Abbas Keramti",
        "instructor_two": "",
        "notes": "this tutorial is for INF1344H lecture 0202",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "TUT",
        "section": "102",
        "day": "Thursday",
        "time": "10-11am",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for INF1344H lecture 0101",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "TUT",
        "section": "103",
        "day": "Thursday",
        "time": "11-12pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for INF1344H lecture 0101",
        "semester": "F"
    },
    {
        "course": "INF1344H",
        "title": "introduction to Statistics for Data Science",
        "sessionType": "TUT",
        "section": "101",
        "day": "Thursday",
        "time": "9-10am",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "this tutorial is for INF1344H lecture 0101",
        "semester": "F"
    },
    {
        "course": "INF1501H",
        "title": "Culture & Technology I",
        "sessionType": "LEC",
        "section": "101",
        "day": "Friday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "Patrick Keilty",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF1602H",
        "title": "Fundamentals of User Experience",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "6:30-9:30pm",
        "method": "Online Sync",
        "instructor": "Olivier St-Cyr",
        "instructor_two": "Velian Pandeliev",
        "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Wednesday afternoon) for all students from September 13, 2021 to October 6, 2021 and one practical studio component which will meet ONCE per week from October 12, 2021 to December 13, 2021.",
        "semester": "F"
    },
    {
        "course": "INF1602H",
        "title": "Fundamentals of User Experience",
        "sessionType": "LEC",
        "section": "101",
        "day": "Wednesday",
        "time": "1-4pm",
        "method": "Online Sync",
        "instructor": "Olivier St-Cyr",
        "instructor_two": "Velian Pandeliev",
        "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Wednesday afternoon) for all students from September 13, 2021 to October 6, 2021 and one practical studio component which will meet ONCE per week from October 12, 2021 to December 13, 2021.",
        "semester": "F"
    },
    {
        "course": "INF1602H",
        "title": "Fundamentals of User Experience",
        "sessionType": "PRA",
        "section": "101",
        "day": "Monday",
        "time": "5:30-7:30pm",
        "method": "In-Person",
        "instructor": "Olivier St-Cyr",
        "instructor_two": "Velian Pandeliev",
        "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Wednesday afternoon) for all students from September 13, 2021 to October 6, 2021 and one practical studio component which will meet ONCE per week from October 12, 2021 to December 13, 2021.",
        "semester": "F"
    },
    {
        "course": "INF1602H",
        "title": "Fundamentals of User Experience",
        "sessionType": "PRA",
        "section": "102",
        "day": "Monday",
        "time": "7:30-9:30pm",
        "method": "In-Person",
        "instructor": "Olivier St-Cyr",
        "instructor_two": "Velian Pandeliev",
        "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Wednesday afternoon) for all students from September 13, 2021 to October 6, 2021 and one practical studio component which will meet ONCE per week from October 12, 2021 to December 13, 2021.",
        "semester": "F"
    },
    {
        "course": "INF1602H",
        "title": "Fundamentals of User Experience",
        "sessionType": "PRA",
        "section": "104",
        "day": "Tuesday",
        "time": "11-1pm",
        "method": "In-Person",
        "instructor": "Olivier St-Cyr",
        "instructor_two": "Velian Pandeliev",
        "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Wednesday afternoon) for all students from September 13, 2021 to October 6, 2021 and one practical studio component which will meet ONCE per week from October 12, 2021 to December 13, 2021.",
        "semester": "F"
    },
    {
        "course": "INF1602H",
        "title": "Fundamentals of User Experience",
        "sessionType": "PRA",
        "section": "103",
        "day": "Tuesday",
        "time": "9-11am",
        "method": "In-Person",
        "instructor": "Olivier St-Cyr",
        "instructor_two": "Velian Pandeliev",
        "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Wednesday afternoon) for all students from September 13, 2021 to October 6, 2021 and one practical studio component which will meet ONCE per week from October 12, 2021 to December 13, 2021.",
        "semester": "F"
    },
    {
        "course": "INF1602H",
        "title": "Fundamentals of User Experience",
        "sessionType": "PRA",
        "section": "105",
        "day": "Wednesday",
        "time": "12-2pm",
        "method": "In-Person",
        "instructor": "Olivier St-Cyr",
        "instructor_two": "Velian Pandeliev",
        "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Wednesday afternoon) for all students from September 13, 2021 to October 6, 2021 and one practical studio component which will meet ONCE per week from October 12, 2021 to December 13, 2021.",
        "semester": "F"
    },
    {
        "course": "INF1602H",
        "title": "Fundamentals of User Experience",
        "sessionType": "PRA",
        "section": "106",
        "day": "Wednesday",
        "time": "2-4pm",
        "method": "In-Person",
        "instructor": "Olivier St-Cyr",
        "instructor_two": "Velian Pandeliev",
        "notes": "**NOTE: INF1602H consists of a lecture component which will meet TWICE per week (Monday evening and Wednesday afternoon) for all students from September 13, 2021 to October 6, 2021 and one practical studio component which will meet ONCE per week from October 12, 2021 to December 13, 2021.",
        "semester": "F"
    },
    {
        "course": "INF2122H",
        "title": "Digital Preservation and Curation",
        "sessionType": "LEC",
        "section": "102",
        "day": "Thursday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2122H",
        "title": "Digital Preservation and Curation",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2124H",
        "title": "Surveillance and Identity",
        "sessionType": "LEC",
        "section": "101",
        "day": "Wednesday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Kenzie Burchell",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2149H",
        "title": "Administrative Decision-Making in Information Organizations",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "1-4pm",
        "method": "Online Sync",
        "instructor": "Chun Wei Choo",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2158H",
        "title": "Management of Corporate and Other Special Information Centres",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "6:30-9:30pm",
        "method": "Online Sync",
        "instructor": "Vicki Whitmell",
        "instructor_two": "Zachary Osborne",
        "notes": "2nd year MI students only",
        "semester": "F"
    },
    {
        "course": "INF2162H",
        "title": "Rare Books & Manuscripts",
        "sessionType": "LEC",
        "section": "101",
        "day": "Wednesday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "2nd year MI students only",
        "semester": "F"
    },
    {
        "course": "INF2164H",
        "title": "UX Research and Design for Video Games",
        "sessionType": "LEC",
        "section": "101",
        "day": "Thursday",
        "time": "10-12pm",
        "method": "Online Sync",
        "instructor": "Velian Pandeliev",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2164H",
        "title": "UX Research and Design for Video Games",
        "sessionType": "TUT",
        "section": "103",
        "day": "Friday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2164H",
        "title": "UX Research and Design for Video Games",
        "sessionType": "TUT",
        "section": "104",
        "day": "Friday",
        "time": "5-6pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2164H",
        "title": "UX Research and Design for Video Games",
        "sessionType": "TUT",
        "section": "101",
        "day": "Tuesday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2164H",
        "title": "UX Research and Design for Video Games",
        "sessionType": "TUT",
        "section": "102",
        "day": "Tuesday",
        "time": "5-6pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2165H",
        "title": "Accessibility and Inclusive Design",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "6:00-9:00pm",
        "method": "Online Sync",
        "instructor": "Jane Motz Hayes",
        "instructor_two": "Catherine Tunney Braeken",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2165H",
        "title": "Accessibility and Inclusive Design",
        "sessionType": "LEC",
        "section": "102",
        "day": "Wednesday",
        "time": "6:30-9:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2166H",
        "title": "Business Process Management and Mining",
        "sessionType": "LEC",
        "section": "101",
        "day": "Friday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "Ziauddin Babar",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2167H",
        "title": "R for Data Science",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "6:30-9:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2169H",
        "title": "User-Centred Information Systems Development",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "10-12pm",
        "method": "Online Sync",
        "instructor": "Anastasia Kuzminykh",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2169H",
        "title": "User-Centred Information Systems Development",
        "sessionType": "TUT",
        "section": "103",
        "day": "Thursday",
        "time": "6:30-7:30pm",
        "method": "In-Person",
        "instructor": "Anastasia Kuzminykh",
        "instructor_two": "",
        "notes": "in-person with online components, students will be rotated through in-person or online b the teaching team",
        "semester": "F"
    },
    {
        "course": "INF2169H",
        "title": "User-Centred Information Systems Development",
        "sessionType": "TUT",
        "section": "101",
        "day": "Wednesday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "Anastasia Kuzminykh",
        "instructor_two": "",
        "notes": "in-person with online components, students will be rotated through in-person or online b the teaching team",
        "semester": "F"
    },
    {
        "course": "INF2169H",
        "title": "User-Centred Information Systems Development",
        "sessionType": "TUT",
        "section": "102",
        "day": "Wednesday",
        "time": "5:15-6:15pm",
        "method": "In-Person",
        "instructor": "Anastasia Kuzminykh",
        "instructor_two": "",
        "notes": "in-person with online components, students will be rotated through in-person or online b the teaching team",
        "semester": "F"
    },
    {
        "course": "INF2170H",
        "title": "Information Architecture",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "6:30-9:30pm",
        "method": "Online Sync",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2170H",
        "title": "Information Architecture",
        "sessionType": "TUT",
        "section": "101",
        "day": "Friday",
        "time": "1-2pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2170H",
        "title": "Information Architecture",
        "sessionType": "TUT",
        "section": "102",
        "day": "Friday",
        "time": "2-3pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2170H",
        "title": "Information Architecture",
        "sessionType": "TUT",
        "section": "103",
        "day": "Saturday",
        "time": "10-11am",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2170H",
        "title": "Information Architecture",
        "sessionType": "TUT",
        "section": "103",
        "day": "Saturday",
        "time": "11-12pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2175H",
        "title": "Managing Organizational Records I",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Fiorella Foscarini",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2175H",
        "title": "Managing Organizational Records I",
        "sessionType": "LEC",
        "section": "901",
        "day": "Tuesday",
        "time": "9-12pm",
        "method": "Online Sync",
        "instructor": "Fiorella Foscarini",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2175H",
        "title": "Managing Organizational Records I",
        "sessionType": "LEC",
        "section": "102",
        "day": "Wednesday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Fiorella Foscarini",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2175H",
        "title": "Managing Organizational Records I",
        "sessionType": "LEC",
        "section": "902",
        "day": "Wednesday",
        "time": "9-12pm",
        "method": "Online Sync",
        "instructor": "Fiorella Foscarini",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "drop in",
        "section": "",
        "day": "Friday",
        "time": "4-6pm",
        "method": "In-Person",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "Drop in available and not mandatory, no need to enrol in ACORN",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "drop in",
        "section": "",
        "day": "Thursday",
        "time": "4-6pm",
        "method": "In-Person",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "Drop in available and not mandatory, no need to enrol in ACORN",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "LEC",
        "section": "101",
        "day": "Friday",
        "time": "2-4pm",
        "method": "Online Sync",
        "instructor": "Chun Wei Choo",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "TUT",
        "section": "101",
        "day": "Wednesday",
        "time": "5-6pm",
        "method": "Online Sync",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "TUT",
        "section": "102",
        "day": "Wednesday",
        "time": "5-6pm",
        "method": "Online Sync",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "TUT",
        "section": "103",
        "day": "Wednesday",
        "time": "5-6pm",
        "method": "Online Sync",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "TUT",
        "section": "104",
        "day": "Wednesday",
        "time": "5-6pm",
        "method": "Online Sync",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "TUT",
        "section": "105",
        "day": "Wednesday",
        "time": "5-6pm",
        "method": "Online Sync",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "TUT",
        "section": "106",
        "day": "Wednesday",
        "time": "5-6pm",
        "method": "Online Sync",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2176H",
        "title": "Information Management in Organizations-Models and Platforms",
        "sessionType": "TUT",
        "section": "107",
        "day": "Wednesday",
        "time": "5-6pm",
        "method": "Online Sync",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2179H",
        "title": "Machine Learning with Applications in Python",
        "sessionType": "LEC",
        "section": "101",
        "day": "Wednesday",
        "time": "6:30-9:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2180H",
        "title": "Archives, Access, Advocacy and Outreach",
        "sessionType": "LEC",
        "section": "101",
        "day": "Friday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Karen Suurtamm",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2190H",
        "title": "Data Analytics: Introduction, Methods and Practical Approaches",
        "sessionType": "LEC",
        "section": "101",
        "day": "Wednesday",
        "time": "10-11am",
        "method": "Online Sync",
        "instructor": "Perikilis Andritsos",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2190H",
        "title": "Data Analytics: Introduction, Methods and Practical Approaches",
        "sessionType": "TUT",
        "section": "105",
        "day": "Friday",
        "time": "10-11am",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2190H",
        "title": "Data Analytics: Introduction, Methods and Practical Approaches",
        "sessionType": "TUT",
        "section": "106",
        "day": "Friday",
        "time": "11-12pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2190H",
        "title": "Data Analytics: Introduction, Methods and Practical Approaches",
        "sessionType": "TUT",
        "section": "104",
        "day": "Friday",
        "time": "9-10am",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2190H",
        "title": "Data Analytics: Introduction, Methods and Practical Approaches",
        "sessionType": "TUT",
        "section": "101",
        "day": "Thursday",
        "time": "1-2pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2190H",
        "title": "Data Analytics: Introduction, Methods and Practical Approaches",
        "sessionType": "TUT",
        "section": "102",
        "day": "Thursday",
        "time": "2-3pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2190H",
        "title": "Data Analytics: Introduction, Methods and Practical Approaches",
        "sessionType": "TUT",
        "section": "103",
        "day": "Thursday",
        "time": "3-4pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2200H",
        "title": "UX Leadership and Influence",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "6:30-9:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2201H",
        "title": "Information and Communication Technologies, Design, and Marginality",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "2-4pm",
        "method": "Online Sync",
        "instructor": "Priyank Chandra",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2201H",
        "title": "Information and Communication Technologies, Design, and Marginality",
        "sessionType": "TUT",
        "section": "102",
        "day": "Monday",
        "time": "10-11am",
        "method": "In-Person",
        "instructor": "Priyank Chandra",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2201H",
        "title": "Information and Communication Technologies, Design, and Marginality",
        "sessionType": "TUT",
        "section": "103",
        "day": "Monday",
        "time": "11-12pm",
        "method": "In-Person",
        "instructor": "Priyank Chandra",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2201H",
        "title": "Information and Communication Technologies, Design, and Marginality",
        "sessionType": "TUT",
        "section": "104",
        "day": "Monday",
        "time": "11-12pm",
        "method": "Online Sync",
        "instructor": "Priyank Chandra",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2201H",
        "title": "Information and Communication Technologies, Design, and Marginality",
        "sessionType": "TUT",
        "section": "101",
        "day": "Monday",
        "time": "9-10am",
        "method": "In-Person",
        "instructor": "Priyank Chandra",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2223H",
        "title": "Open Government and Research Data",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "Seamus Ross",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2230H",
        "title": "Just Sustainability Design",
        "sessionType": "drop in",
        "section": "",
        "day": "Tuesday",
        "time": "4-6pm",
        "method": "In-Person",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "Drop in available and not mandatory, 2nd+ year students only, no need to enrol in ACORN",
        "semester": "F"
    },
    {
        "course": "INF2230H",
        "title": "Just Sustainability Design",
        "sessionType": "LEC",
        "section": "101",
        "day": "Wednesday",
        "time": "1-4pm",
        "method": "Online Sync",
        "instructor": "Christoph Becker",
        "instructor_two": "",
        "notes": "2nd+ year students only",
        "semester": "F"
    },
    {
        "course": "INF2240H",
        "title": "Political Economy and Cultural Studies of Information",
        "sessionType": "drop in",
        "section": "",
        "day": "Wednesday",
        "time": "2-4pm",
        "method": "In-Person",
        "instructor": "No instructor",
        "instructor_two": "",
        "notes": "Drop in available and not mandatory, no need to enrol in ACORN",
        "semester": "F"
    },
    {
        "course": "INF2240H",
        "title": "Political Economy and Cultural Studies of Information",
        "sessionType": "LEC",
        "section": "101",
        "day": "Thursday",
        "time": "9-12pm",
        "method": "Online Sync",
        "instructor": "Nicole Cohen",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2312H",
        "title": "Art Librarianship in Theory and Practice",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "6:30-9:30pm",
        "method": "In-Person",
        "instructor": "Daniel Payne",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2314H",
        "title": "Program Evaluation",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Kim Silk",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2316H",
        "title": "Critical Studies of Social Media",
        "sessionType": "LEC",
        "section": "101",
        "day": "",
        "time": "",
        "method": "Online Async",
        "instructor": "Tero Karppi",
        "instructor_two": "",
        "notes": "does not meet on Wednesdays from 6:30-9:30pm, does not meet on specific days and times",
        "semester": "F"
    },
    {
        "course": "INF2316H",
        "title": "Critical Studies of Social Media",
        "sessionType": "TUT",
        "section": "101",
        "day": "Thursday",
        "time": "10-11:30am",
        "method": "In-Person",
        "instructor": "Tero Karppi",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2316H",
        "title": "Critical Studies of Social Media",
        "sessionType": "TUT",
        "section": "102",
        "day": "Thursday",
        "time": "11:30-1pm",
        "method": "In-Person",
        "instructor": "Tero Karppi",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2401H",
        "title": "Special Topics in Information",
        "subtitle": "Coded Culture: The Rise of Digital Media Platforms",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2405H",
        "title": "Special Topics in Information",
        "subtitle": "Science and Policy Integration for Evidence-Based Policy Making",
        "sessionType": "LEC",
        "section": "101",
        "day": "Thursday",
        "time": "6:30-9:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2XXXH",
        "title": "Human-Centred Topic Models",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "10-12pm",
        "method": "In-Person",
        "instructor": "Shion Guha",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2XXXH",
        "title": "Knowledge Organization, Equity and Justice",
        "sessionType": "LEC",
        "section": "101",
        "day": "Thursday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Stacy Allison-Cassin",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2XXXH",
        "title": "Human-Centred Topic Models",
        "sessionType": "TUT",
        "section": "101",
        "day": "Friday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF2XXXH",
        "title": "Human-Centred Topic Models",
        "sessionType": "TUT",
        "section": "102",
        "day": "Friday",
        "time": "5-6pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "INF3001H",
        "title": "Research in Information - Foundations",
        "sessionType": "LEC",
        "section": "101",
        "day": "Wednesday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "Patrick Keilty",
        "instructor_two": "",
        "notes": "PhD students only",
        "semester": "F"
    },
    {
        "course": "INF3014H",
        "title": "Cultural Interpretive Methods for Media and Technology",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "TL Cowan",
        "instructor_two": "",
        "notes": "PhD students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "LEC",
        "section": "101",
        "day": "Thursday",
        "time": "1-4pm",
        "method": "Online Sync",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "102",
        "day": "Monday",
        "time": "10-11am",
        "method": "In-Person",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "103",
        "day": "Monday",
        "time": "11-12pm",
        "method": "In-Person",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "104",
        "day": "Monday",
        "time": "12-1pm",
        "method": "In-Person",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "105",
        "day": "Monday",
        "time": "1-2pm",
        "method": "In-Person",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "101",
        "day": "Monday",
        "time": "9-10am",
        "method": "In-Person",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "107",
        "day": "Wednesday",
        "time": "10-11am",
        "method": "Online Sync",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "108",
        "day": "Wednesday",
        "time": "11-12pm",
        "method": "Online Sync",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "109",
        "day": "Wednesday",
        "time": "12-1pm",
        "method": "Online Sync",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "110",
        "day": "Wednesday",
        "time": "1-2pm",
        "method": "Online Sync",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3900H",
        "title": "The Emerging Professional",
        "sessionType": "TUT",
        "section": "106",
        "day": "Wednesday",
        "time": "9-10am",
        "method": "Online Sync",
        "instructor": "Colin Furness",
        "instructor_two": "",
        "notes": "MI students only",
        "semester": "F"
    },
    {
        "course": "INF3XXXH",
        "title": "Ethics of AI",
        "sessionType": "LEC",
        "section": "101",
        "day": "Friday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Brian Cantwell Smith",
        "instructor_two": "",
        "notes": "PhD students only, pending final approval",
        "semester": "F"
    },
    {
        "course": "MSL2000H",
        "title": "Curatorial Practice",
        "sessionType": "LEC",
        "section": "101",
        "day": "Friday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2255H",
        "title": "Social Digital Memory",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Costis Dallas",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2330H",
        "title": "Interpretation and Meaning-Making in Museums",
        "sessionType": "LEC",
        "section": "101",
        "day": "",
        "time": "",
        "method": "Online Async",
        "instructor": "Irina Mihalache",
        "instructor_two": "",
        "notes": "does not meet on Thursdays from 1-4pm, does not meet on specific days and times",
        "semester": "F"
    },
    {
        "course": "MSL2330H",
        "title": "Interpretation and Meaning-Making in Museums",
        "sessionType": "TUT",
        "section": "101",
        "day": "Wednesday",
        "time": "1:30-2:30pm",
        "method": "In-Person",
        "instructor": "Irina Mihalache",
        "instructor_two": "",
        "notes": "in-person tutorial, meets on Wednesdays from 1:30-2:30pm",
        "semester": "F"
    },
    {
        "course": "MSL2330H",
        "title": "Interpretation and Meaning-Making in Museums",
        "sessionType": "TUT",
        "section": "102",
        "day": "Wednesday",
        "time": "3-4pm",
        "method": "In-Person",
        "instructor": "Irina Mihalache",
        "instructor_two": "",
        "notes": "in-person tutorial, meets on Wednesdays from 3-4pm",
        "semester": "F"
    },
    {
        "course": "MSL2331H",
        "title": "The Museum Exhibition: Histories, Practices, Genres",
        "sessionType": "LEC",
        "section": "101",
        "day": "",
        "time": "",
        "method": "Online Async",
        "instructor": "Irina Mihalache",
        "instructor_two": "",
        "notes": "does not meet on Wednesdays from 1-4pm, doe not meet on specific days and times",
        "semester": "F"
    },
    {
        "course": "MSL2331H",
        "title": "The Museum Exhibition: Histories, Practices, Genres",
        "sessionType": "TUT",
        "section": "101",
        "day": "Tuesday",
        "time": "1-2pm",
        "method": "Online Sync",
        "instructor": "Irina Mihalache",
        "instructor_two": "",
        "notes": "remote tutorial, meets online remotely on Tuesday from 1-2pm",
        "semester": "F"
    },
    {
        "course": "MSL2331H",
        "title": "The Museum Exhibition: Histories, Practices, Genres",
        "sessionType": "TUT",
        "section": "102",
        "day": "Tuesday",
        "time": "2-3pm",
        "method": "In-Person",
        "instructor": "Irina Mihalache",
        "instructor_two": "",
        "notes": "in-person tutorial, meets on Tuesdsays from 2-3pm",
        "semester": "F"
    },
    {
        "course": "MSL2331H",
        "title": "The Museum Exhibition: Histories, Practices, Genres",
        "sessionType": "TUT",
        "section": "103",
        "day": "Tuesday",
        "time": "3-4pm",
        "method": "In-Person",
        "instructor": "Irina Mihalache",
        "instructor_two": "",
        "notes": "in-person tutorial, meets on Tuesdays from 3-4pm",
        "semester": "F"
    },
    {
        "course": "MSL2332H",
        "title": "Public Programs and Education",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2350H",
        "title": "Museum Planning and Management: Projects and Fundraising",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "9-12pm",
        "method": "Online Sync",
        "instructor": "Costis Dallas",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2350H",
        "title": "Museum Planning and Management: Projects and Fundraising",
        "sessionType": "TUT",
        "section": "101",
        "day": "Monday",
        "time": "4-5pm",
        "method": "In-Person",
        "instructor": "Costis Dallas",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2350H",
        "title": "Museum Planning and Management: Projects and Fundraising",
        "sessionType": "TUT",
        "section": "102",
        "day": "Monday",
        "time": "5-6pm",
        "method": "In-Person",
        "instructor": "Costis Dallas",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2360H",
        "title": "Museums and Indigenous Communities: Changing Relations, Changing Practice",
        "sessionType": "LEC",
        "section": "101",
        "day": "Tuesday",
        "time": "6:30-9:30pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2370H",
        "title": "Museums and Cultural Heritage: Context and Critical Issues",
        "sessionType": "LEC",
        "section": "101",
        "day": "Wednesday",
        "time": "9-10am",
        "method": "Online Sync",
        "instructor": "Cara Krmpotich",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2370H",
        "title": "Museums and Cultural Heritage: Context and Critical Issues",
        "sessionType": "TUT",
        "section": "103",
        "day": "Friday",
        "time": "4-6pm",
        "method": "In-Person",
        "instructor": "Cara Krmpotich",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2370H",
        "title": "Museums and Cultural Heritage: Context and Critical Issues",
        "sessionType": "TUT",
        "section": "101",
        "day": "Tuesday",
        "time": "4-6pm",
        "method": "In-Person",
        "instructor": "Cara Krmpotich",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL2370H",
        "title": "Museums and Cultural Heritage: Context and Critical Issues",
        "sessionType": "TUT",
        "section": "102",
        "day": "Wednesday",
        "time": "10-12pm",
        "method": "Online Sync",
        "instructor": "Cara Krmpotich",
        "instructor_two": "",
        "notes": "",
        "semester": "F"
    },
    {
        "course": "MSL3000H",
        "title": "Internship",
        "sessionType": "LEC",
        "section": "101",
        "day": "Friday",
        "time": "1-4pm",
        "method": "In-Person",
        "instructor": "TBD",
        "instructor_two": "",
        "notes": "full year course, 2nd year MMSt students only",
        "semester": "F"
    },
    {
        "course": "MSL3900H",
        "title": "The Emerging Professional",
        "sessionType": "LEC",
        "section": "101",
        "day": "Monday",
        "time": "6:30-9:30pm",
        "method": "In-Person",
        "instructor": "John Summers",
        "instructor_two": "",
        "notes": "MMSt students only",
        "semester": "F"
    },
    {
        "course": "MSL4000Y",
        "title": "Exhibition Project",
        "sessionType": "LEC",
        "section": "101",
        "day": "Thursday",
        "time": "9-12pm",
        "method": "In-Person",
        "instructor": "Cara Krmpotich",
        "instructor_two": "Irina Mihalache",
        "notes": "in-person with online components, 2nd year MMSt students only"
    }
]