export const COURSES = [
        {
            "course": "Course Code",
            "title": "Course Title",
            "subtitle": "Subtitle",
            "sessionType": "LEC\/PRA\/TUT",
            "section": "Section",
            "credit": "Credit",
            "required_course_1": "Required Course",
            "required_course_2": "Required Course",
            "required_course_3": "Required Course",
            "day_1": "day_1 ",
            "start_time_1": "Start Time",
            "end_time_1": "End Time",
            "method": "Delivery Method",
            "instructor": "Instructor",
            "instructor_two": "Instructor",
            "notes": "Notes"
        },
        {
            "course": "BKS1002H",
            "title": "Book History in Practice",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "BHPC collaborative specialization",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "2:00pm",
            "end_time_1": "5:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "Course is reserved for BHPC students but non-BHPC students may be able to take it by permission of the instructor"
        },
        {
            "course": "INF1003H",
            "title": "Information Systems, Services and Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": "KMIM",
            "required_course_3": "GPO",
            "day_1": "Monday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Kelly Lyons",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Unanticipated Consequences of IT",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "The Internet of Things",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "10:00am",
            "end_time_1": "1:00pm",
            "method": "In-Person",
            "instructor": "Maher Elshakankiri",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Systems Thinking, Systems Design",
            "sessionType": "LEC",
            "section": 103,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Christoph Becker",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Information and Contemplation",
            "sessionType": "LEC",
            "section": 104,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Jenna Hartel",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Adopting DevOps for Large-Scale Information Systems",
            "sessionType": "LEC",
            "section": 105,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Safwat Hassan",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Information and the World of Work",
            "sessionType": "LEC",
            "section": 106,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Methods and Memory Work",
            "sessionType": "LEC",
            "section": 107,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "3:30pm",
            "method": "In-Person",
            "instructor": "SA Smythe",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Trauma-Informed Information Practices",
            "sessionType": "LEC",
            "section": 108,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Primary Source Research as Inquiry: Storytelling, Memory, and Authenticity ",
            "sessionType": "LEC",
            "section": 109,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Truth and Reconciliation, Commission, Museums and Archives",
            "sessionType": "LEC",
            "section": 110,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Queer Art and Archives",
            "sessionType": "LEC",
            "section": 111,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": "TBD",
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Exploring Outreach: Sharing Collections, Engaging the Public, and Encouraging Participatory Approaches",
            "sessionType": "LEC",
            "section": 112,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "4:00pm",
            "end_time_1": "6:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Reading and Unreading Digital-Born Creative Works: Critical Making of Contemporary Information",
            "sessionType": "LEC",
            "section": 113,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Best Practices in Data Visualization ",
            "sessionType": "LEC",
            "section": 114,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Graphic Design for UX",
            "sessionType": "LEC",
            "section": 115,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Relationship-Based Archival Access Systems",
            "sessionType": "LEC",
            "section": 116,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Wendy Duff",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Graphic Design for UX",
            "sessionType": "LEC",
            "section": 117,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "title": "Information Workshop I",
            "subtitle": "Creating and Exploring Software Environments with JavaScript and Node.js",
            "sessionType": "LEC",
            "section": 118,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Unanticipated Consequences of IT",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "The Internet of Things",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "10:00am",
            "end_time_1": "1:00pm",
            "method": "In-Person",
            "instructor": "Maher Elshakankiri",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Systems Thinking, Systems Design",
            "sessionType": "LEC",
            "section": 103,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Christoph Becker",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Information and Contemplation",
            "sessionType": "LEC",
            "section": 104,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Jenna Hartel",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Adopting DevOps for Large-Scale Information Systems",
            "sessionType": "LEC",
            "section": 105,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Safwat Hassan",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Information and the World of Work",
            "sessionType": "LEC",
            "section": 106,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Methods and Memory Work",
            "sessionType": "LEC",
            "section": 107,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "3:30pm",
            "method": "In-Person",
            "instructor": "SA Smythe",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Trauma-Informed Information Practices",
            "sessionType": "LEC",
            "section": 108,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Primary Source Research as Inquiry: Storytelling, Memory, and Authenticity ",
            "sessionType": "LEC",
            "section": 109,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Truth and Reconciliation, Commission, Museums and Archives",
            "sessionType": "LEC",
            "section": 110,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Queer Art and Archives",
            "sessionType": "LEC",
            "section": 111,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": "TBD",
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Exploring Outreach: Sharing Collections, Engaging the Public, and Encouraging Participatory Approaches",
            "sessionType": "LEC",
            "section": 112,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "4:00pm",
            "end_time_1": "6:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Reading and Unreading Digital-Born Creative Works: Critical Making of Contemporary Information",
            "sessionType": "LEC",
            "section": 113,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Best Practices in Data Visualization ",
            "sessionType": "LEC",
            "section": 114,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Graphic Design for UX",
            "sessionType": "LEC",
            "section": 115,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop II",
            "subtitle": "Relationship-Based Archival Access Systems",
            "sessionType": "LEC",
            "section": 116,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Wendy Duff",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop ii",
            "subtitle": "Graphic Design for UX",
            "sessionType": "LEC",
            "section": 117,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "title": "Information Workshop ii",
            "subtitle": "Creating and Exploring Software Environments with JavaScript and Node.js",
            "sessionType": "LEC",
            "section": 118,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:39pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1230H",
            "title": "Management of Information Organizations",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "KMIM",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Victoria Owen",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1240H",
            "title": "Research Methods",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "THESIS",
            "required_course_2": "GPO",
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Malayna Bernstein",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1322H",
            "title": "Community & Values",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "LIS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Nadia Caidi",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1322H",
            "title": "Community & Values",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "LIS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Nadia Caidi",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1324H",
            "title": "Critical Infrastructures",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "LIS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Siobhan Stevenson",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1324H",
            "title": "Critical Infrastructures",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "LIS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Siobhan Stevenson",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1331H",
            "title": "Archival Arrangements and Description",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1342H",
            "title": "Systems Requirements and Architectural Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ISD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Christoph Becker",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1342H",
            "title": "Systems Requirements and Architectural Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "ISD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Christoph Becker",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1343H",
            "title": "Data Modelling and Data Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ISD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "10:00am",
            "end_time_1": "1:00pm",
            "method": "In-Person",
            "instructor": "Maher Elshakankiri",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1343H",
            "title": "Data Modelling and Data Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "ISD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "2:00pm",
            "end_time_1": "5:00pm",
            "method": "In-Person",
            "instructor": "Maher Elshakankiri",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF1502H",
            "title": "Culture & Technology II",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "C&T",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Matt Ratto",
            "instructor_two": null,
            "notes": "2nd year MI students only"
        },
        {
            "course": "INF2040H",
            "title": "Project Management",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2040H",
            "title": "Project Management",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2120H",
            "title": "Conservation and Preservation of Recorded Information",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2121H",
            "title": "Specialized Archives",
            "subtitle": "Black Studies and the Archive",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "SA Smythe",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2127H",
            "title": "Collection, Development, Evaluation, and Management",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2141H",
            "title": "Children's Cultural Texts and Artifacts",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "2:00pm",
            "end_time_1": "5:00pm",
            "method": "In-Person",
            "instructor": "Sara Grimes",
            "instructor_two": " ",
            "notes": null
        },
        {
            "course": "INF2145H",
            "title": "Creation and Organization of Bibliographic Records",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2162H",
            "title": "Rare Books and Manuscripts",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "2nd+ year students only"
        },
        {
            "course": "INF2164H",
            "title": "UX Research and Design for Video Games",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Velian Pandeliev",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2169H",
            "title": "User-Centred Information Systems Development",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "11:00am",
            "end_time_1": "1:00pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2169H",
            "title": "User-Centred Information Systems Development",
            "subtitle": null,
            "sessionType": "TUT",
            "section": 101,
            "credit": 0,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "4:00pm",
            "end_time_1": "5:00pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2169H",
            "title": "User-Centred Information Systems Development",
            "subtitle": null,
            "sessionType": "TUT",
            "section": 102,
            "credit": 0,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "5:15pm",
            "end_time_1": "6:15pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2169H",
            "title": "User-Centred Information Systems Development",
            "subtitle": null,
            "sessionType": "TUT",
            "section": 103,
            "credit": 0,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "4:00pm",
            "end_time_1": "5:00pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2169H",
            "title": "User-Centred Information Systems Development",
            "subtitle": null,
            "sessionType": "TUT",
            "section": 104,
            "credit": 0,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "5:15pm",
            "end_time_1": "6:15pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2169H",
            "title": "User-Centred Information Systems Development",
            "subtitle": null,
            "sessionType": "TUT",
            "section": 105,
            "credit": 0,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "4:00pm",
            "end_time_1": "5:00pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2169H",
            "title": "User-Centred Information Systems Development",
            "subtitle": null,
            "sessionType": "TUT",
            "section": 106,
            "credit": 0,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "5:15pm",
            "end_time_1": "6:15pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2171H",
            "title": "Usability Assessment: Concepts, Methods and Tools",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2171H",
            "title": "Usability Assessment: Concepts, Methods and Tools",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2172H",
            "title": "Reader Advisory: Reference Work and Resources",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2173H",
            "title": "Information Professional Practicum",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "2nd+ year MI students only"
        },
        {
            "course": "INF2175H",
            "title": "Managing Organizational Records I",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": "KMIM",
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2177H ",
            "title": "Information Management and Systems",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ISD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Safwat Hassan",
            "instructor_two": null,
            "notes": "recommended to be taken in 2nd year"
        },
        {
            "course": "INF2178H",
            "title": "Experimental Design for Data Science",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "HCDS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Shion Guha",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2181H",
            "title": "Information, Policy, Regulation, and Law",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "CIPS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Victoria Owen",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2184H",
            "title": "Appraisal for Records Retention and Archives Acquisition",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "4:00pm",
            "end_time_1": "6:00pm",
            "method": "In-Person",
            "instructor": "Fiorella Foscarini",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2184H",
            "title": "Appraisal for Records Retention and Archives Acquisition",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "3:00pm",
            "method": "In-Person",
            "instructor": "Fiorella Foscarini",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2185H",
            "title": "Libraries, Archives, Museums: Intersections and Tensions",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Heather MacNeil",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2186H",
            "title": "Metadata Schemas and Applications",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "8:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2186H",
            "title": "Metadata Schemas and Applications",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "6:30pm",
            "end_time_1": "8:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2191H",
            "title": "User Interface Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Velian Pandeliev",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2191H",
            "title": "User Interface Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Velian Pandeliev",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2191H",
            "title": "User Interface Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 103,
            "credit": 0.5,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Velian Pandeliev",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2192H",
            "title": "Representing UX",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Priyank Chandra",
            "instructor_two": null,
            "notes": "2nd year MI students only"
        },
        {
            "course": "INF2192H",
            "title": "Representing UX",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "UXD",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Priyank Chandra",
            "instructor_two": null,
            "notes": "2nd year MI students only"
        },
        {
            "course": "INF2200H",
            "title": "UX Leadership and Influence",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": "TBD",
            "notes": null
        },
        {
            "course": "INF2202H",
            "title": "Data Governance in the World of Big Data",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2205H",
            "title": "Designing Sustainable & Resilient Machine Learning Systems with MLOps",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2210H",
            "title": "Human Values in Data Science",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "HCDS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Tegan Maharaj",
            "instructor_two": null,
            "notes": "2nd year MI students only"
        },
        {
            "course": "INF2210H",
            "title": "Human Values in Data Science",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "HCDS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Seamus Ross",
            "instructor_two": null,
            "notes": "2nd year MI students only"
        },
        {
            "course": "INF2224H",
            "title": "Service Design",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2225H",
            "title": "Digital Discourse",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Patrick Keilty",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2234H",
            "title": "Academic Librarianship",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2235H",
            "title": "Outer Space and the City",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Marie Pier Boucher",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2239H",
            "title": "Information, Misinformation & Health",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Colin Furness",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2242H",
            "title": "Studying Information and Knowledge Practices",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "CIPS",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Negin Dahya",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2243H",
            "title": "Critical Histories of Information and Communication Technologies",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "CIPS",
            "required_course_2": "C&T",
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Alan Galey",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2245H",
            "title": "Platforms: Global Histories, Practices, and Theories",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Julie Chen",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2250H",
            "title": "Copyright for Information Professionals",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2256H",
            "title": "Digital Scholarship",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Christopher Young",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2311H",
            "title": "Managing AudioVisual Material",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "Rachel Beattie",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2313H",
            "title": "Service Science",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Kelly Lyons",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2320H",
            "title": "Remix Culture",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "C&T",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Sara Grimes",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2330H",
            "title": "Information Ethnography",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Jenna Hartel",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2331H",
            "title": "The Future of the Book",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "C&T",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Alan Galey",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF2403H",
            "title": "Special Topics in Information",
            "subtitle": "Digital Archives Workflows",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "2nd year MI students only"
        },
        {
            "course": "INF2406H",
            "title": "Special Topics in Information",
            "subtitle": "Special Topics in Information: Issues in Health Data Science and AI",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "10:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Aviv Shachak",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "INF3010H",
            "title": "Power, Media, and Technology",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "PhD students only"
        },
        {
            "course": "INF3012H",
            "title": "Social Scientific Methods for Media",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Jeff Boase",
            "instructor_two": null,
            "notes": "PhD students only"
        },
        {
            "course": "INF3XXXH",
            "title": "Elective",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Rohan Alexander",
            "instructor_two": null,
            "notes": "PhD students only, course is in development and is research methods related to stats, needs approval"
        },
        {
            "course": "KMD1002H",
            "title": "Applications in Knowledge Media",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "KMD collaborative specialization",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "4:00pm",
            "end_time_1": "6:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "KMD CS students have priority"
        },
        {
            "course": "MSL1150H",
            "title": "Collection Management",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "MMSt",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Costis Dallas",
            "instructor_two": "Cara Krmpotich",
            "notes": null
        },
        {
            "course": "MSL1150H",
            "title": "Collection Management",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "MMSt",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Tuesday_1 ",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Costis Dallas",
            "instructor_two": "Cara Krmpotich",
            "notes": null
        },
        {
            "course": "MSL1230H",
            "title": "Ethics, Leadership, and Management",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "MMSt",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Costis Dallas",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "MSL1350H",
            "title": "Museum and Their Public",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "MSL2050H",
            "title": "Curating Science",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday_1s",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "MSL2100H",
            "title": "Museum Environment ",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Friday",
            "start_time_1": "9:00am",
            "end_time_1": "5:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": "intensive, 6 weeks, 9-5pm on Friday_1s"
        },
        {
            "course": "MSL2230H",
            "title": "Nature & Culture: Histories of Heritage Interpretation in North America",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "MSL2326H",
            "title": "Artifact, Audience, and Text: Writing in the Museum",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "6:30pm",
            "end_time_1": "9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "MSL2335H",
            "title": "The Digital Museum: From Strategy to Implementation",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Monday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "MSL2340H",
            "title": "Issues in Cultural Policy and Contemporary Culture",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": null,
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Wednesday",
            "start_time_1": "1:00pm",
            "end_time_1": "4:00pm",
            "method": "In-Person",
            "instructor": "Alan Stanbridge",
            "instructor_two": null,
            "notes": null
        },
        {
            "course": "MSL4000Y",
            "title": "Museum Studies Capstone Projects",
            "subtitle": null,
            "sessionType": "LEC",
            "section": 101,
            "credit": 1,
            "required_course_1": "MMSt",
            "required_course_2": null,
            "required_course_3": null,
            "day_1": "Thursday",
            "start_time_1": "9:00am",
            "end_time_1": "12:00pm",
            "method": "In-Person",
            "instructor": "Cara Krmpotich",
            "instructor_two": "Morgan Mavis",
            "notes": "2nd+ year MMSt students only"
        }
]