export const COURSES = [
        {
            "course": "Course Code",
            "semester": "Session Code",
            "title": "Course Title",
            "subtitle": "Subtitle",
            "sessionType": "LEC/PRA/TUT",
            "section": "Section",
            "credit": "Credit",
            "required_course_1": "Required Course",
            "required_course_2": "Required Course",
            "required_course_3": "Required Course",
            "day": "Day",
            "time": "Start Time",
            "method": "Delivery Method",
            "instructor": "Instructor",
            "instructor_two": "Instructor",
            "notes": "Notes"
        },
        {
            "course": "BKS1002H",
            "semester": "S",
            "title": "Book History in Practice",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "BHPC collaborative specialization",
            "day": "Monday",
            "Column12": "2-5pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "Course is reserved for BHPC students but non-BHPC students may be able to take it by permission of the instructor"
        },
        {
            "course": "INF1003H",
            "semester": "S",
            "title": "Information Systems, Services and Design",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": "KMIM",
            "required_course_3": "GPO",
            "day": "Monday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Kelly Lyons"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Unanticipated Consequences of IT",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Monday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "The Internet of Things",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Monday",
            "Column12": "10-1pm",
            "method": "In-Person",
            "instructor": "Maher Elshakankiri",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Systems Thinking, Systems Design",
            "sessionType": "LEC",
            "section": 103,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Tuesday ",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Christoph Becker",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Information and Contemplation",
            "sessionType": "LEC",
            "section": 104,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Jenna Hartel",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Adopting DevOps for Large-Scale Information Systems",
            "sessionType": "LEC",
            "section": 105,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Safwat Hassan",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Information and the World of Work",
            "sessionType": "LEC",
            "section": 106,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Methods and Memory Work",
            "sessionType": "LEC",
            "section": 107,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "1-3:30pm",
            "method": "In-Person",
            "instructor": "SA Smythe",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Trauma-Informed Information Practices",
            "sessionType": "LEC",
            "section": 108,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Primary Source Research as Inquiry: Storytelling, Memory, and Authenticity ",
            "sessionType": "LEC",
            "section": 109,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Truth and Reconciliation, Commission, Museums and Archives",
            "sessionType": "LEC",
            "section": 110,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Queer Art and Archives",
            "sessionType": "LEC",
            "section": 111,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Exploring Outreach: Sharing Collections, Engaging the Public, and Encouraging Participatory Approaches",
            "sessionType": "LEC",
            "section": 112,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "4-6:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Reading and Unreading Digital-Born Creative Works: Critical Making of Contemporary Information",
            "sessionType": "LEC",
            "section": 113,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Best Practices in Data Visualization ",
            "sessionType": "LEC",
            "section": 114,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Graphic Design for UX",
            "sessionType": "LEC",
            "section": 115,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Friday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Supporting Researchers Investigating Difficult Histories: A Relationship-Based Access System",
            "sessionType": "LEC",
            "section": 116,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Tuesday ",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Wendy Duff",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1005H",
            "semester": "S",
            "title": "Information Workshop I",
            "subtitle": "Creating and Exploring Software Environments with JavaScript and Node.js",
            "sessionType": "LEC",
            "section": 118,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of January 9, 2023 to week of February 13, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Unanticipated Consequences of IT",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Monday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "The Internet of Things",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Monday",
            "Column12": "10-1pm",
            "method": "In-Person",
            "instructor": "Maher Elshakankiri",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Systems Thinking, Systems Design",
            "sessionType": "LEC",
            "section": 103,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Tuesday ",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Christoph Becker",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Information and Contemplation",
            "sessionType": "LEC",
            "section": 104,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Jenna Hartel",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Adopting DevOps for Large-Scale Information Systems",
            "sessionType": "LEC",
            "section": 105,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Safwat Hassan",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Information and the World of Work",
            "sessionType": "LEC",
            "section": 106,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Methods and Memory Work",
            "sessionType": "LEC",
            "section": 107,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "1-3:30pm",
            "method": "In-Person",
            "instructor": "SA Smythe",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Trauma-Informed Information Practices",
            "sessionType": "LEC",
            "section": 108,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Primary Source Research as Inquiry: Storytelling, Memory, and Authenticity ",
            "sessionType": "LEC",
            "section": 109,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Truth and Reconciliation, Commission, Museums and Archives",
            "sessionType": "LEC",
            "section": 110,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Queer Art and Archives",
            "sessionType": "LEC",
            "section": 111,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Exploring Outreach: Sharing Collections, Engaging the Public, and Encouraging Participatory Approaches",
            "sessionType": "LEC",
            "section": 112,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "4-6:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Reading and Unreading Digital-Born Creative Works: Critical Making of Contemporary Information",
            "sessionType": "LEC",
            "section": 113,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Best Practices in Data Visualization ",
            "sessionType": "LEC",
            "section": 114,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Graphic Design for UX",
            "sessionType": "LEC",
            "section": 115,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Friday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Supporting Researchers Investigating Difficult Histories: A Relationship-Based Access System",
            "sessionType": "LEC",
            "section": 116,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Tuesday ",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Wendy Duff",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1006H",
            "semester": "S",
            "title": "Information Workshop II",
            "subtitle": "Creating and Exploring Software Environments with JavaScript and Node.js",
            "sessionType": "LEC",
            "section": 118,
            "credit": 0.25,
            "required_course_1": "ALL concentrations",
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "week of February 27, 2023 to week of April 3, 2023"
        },
        {
            "course": "INF1230H",
            "semester": "S",
            "title": "Management of Information Organizations",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "KMIM",
            "day": "Friday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Victoria Owen"
        },
        {
            "course": "INF1240H",
            "semester": "S",
            "title": "Research Methods",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "THESIS",
            "required_course_2": "GPO",
            "day": "Tuesday ",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Malayna Bernstein"
        },
        {
            "course": "INF1322H",
            "semester": "S",
            "title": "Community & Values",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "LIS",
            "day": "Tuesday ",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Nadia Caidi"
        },
        {
            "course": "INF1322H",
            "semester": "S",
            "title": "Community & Values",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "LIS",
            "day": "Thursday ",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Nadia Caidi"
        },
        {
            "course": "INF1324H",
            "semester": "S",
            "title": "Critical Infrastructures",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "LIS",
            "day": "Tuesday ",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Siobhan Stevenson"
        },
        {
            "course": "INF1324H",
            "semester": "S",
            "title": "Critical Infrastructures",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "LIS",
            "day": "Wednesday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Siobhan Stevenson"
        },
        {
            "course": "INF1331H",
            "semester": "S",
            "title": "Archival Arrangements and Description",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF1342H",
            "semester": "S",
            "title": "Systems Requirements and Architectural Design",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ISD",
            "day": "Monday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Christoph Becker"
        },
        {
            "course": "INF1342H",
            "semester": "S",
            "title": "Systems Requirements and Architectural Design",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "ISD",
            "day": "Wednesday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Christoph Becker"
        },
        {
            "course": "INF1343H",
            "semester": "S",
            "title": "Data Modelling and Data Design",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ISD",
            "day": "Thursday",
            "Column12": "10-1pm",
            "method": "In-Person",
            "instructor": "Maher Elshakankiri"
        },
        {
            "course": "INF1343H",
            "semester": "S",
            "title": "Data Modelling and Data Design",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "ISD",
            "day": "Thursday",
            "Column12": "2-5pm",
            "method": "In-Person",
            "instructor": "Maher Elshakankiri"
        },
        {
            "course": "INF1502H",
            "semester": "S",
            "title": "Culture & Technology II",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "C&T",
            "day": "Monday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Matt Ratto",
            "Column17": "2nd+ year MI students only"
        },
        {
            "course": "INF2040H",
            "semester": "S",
            "title": "Project Management",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "day": "Friday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2040H",
            "semester": "S",
            "title": "Project Management",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Tuesday ",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2120H",
            "semester": "S",
            "title": "Conservation and Preservation of Recorded Information",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2121H",
            "semester": "S",
            "title": "Specialized Archives",
            "subtitle": "Black Studies and the Archive",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Tuesday ",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "SA Smythe"
        },
        {
            "course": "INF2127H",
            "semester": "S",
            "title": "Collection, Development, Evaluation, and Management",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2141H",
            "semester": "S",
            "title": "Children's Cultural Texts and Artifacts",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "2-5pm",
            "method": "In-Person",
            "instructor": "Sara Grimes",
            "instructor_two": " "
        },
        {
            "course": "INF2145H",
            "semester": "S",
            "title": "Creation and Organization of Bibliographic Records",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2162H",
            "semester": "S",
            "title": "Rare Books and Manuscripts",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Thursday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "2nd+ year students only"
        },
        {
            "course": "INF2164H",
            "semester": "S",
            "title": "UX Research and Design for Video Games",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Friday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Velian Pandeliev"
        },
        {
            "course": "INF2169H",
            "semester": "S",
            "title": "User-Centred Information Systems Development",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "UXD",
            "day": "Monday",
            "Column12": "11-1pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh"
        },
        {
            "course": "INF2169H",
            "semester": "S",
            "title": "User-Centred Information Systems Development",
            "sessionType": "TUT",
            "section": 101,
            "credit": 0,
            "required_course_1": "UXD",
            "day": "Monday",
            "Column12": "4-5pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh"
        },
        {
            "course": "INF2169H",
            "semester": "S",
            "title": "User-Centred Information Systems Development",
            "sessionType": "TUT",
            "section": 102,
            "credit": 0,
            "required_course_1": "UXD",
            "day": "Monday",
            "Column12": "5:15-6:15pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh"
        },
        {
            "course": "INF2169H",
            "semester": "S",
            "title": "User-Centred Information Systems Development",
            "sessionType": "TUT",
            "section": 103,
            "credit": 0,
            "required_course_1": "UXD",
            "day": "Tuesday ",
            "Column12": "4-5pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh"
        },
        {
            "course": "INF2169H",
            "semester": "S",
            "title": "User-Centred Information Systems Development",
            "sessionType": "TUT",
            "section": 104,
            "credit": 0,
            "required_course_1": "UXD",
            "day": "Tuesday ",
            "Column12": "5:15-6:15pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh"
        },
        {
            "course": "INF2169H",
            "semester": "S",
            "title": "User-Centred Information Systems Development",
            "sessionType": "TUT",
            "section": 105,
            "credit": 0,
            "required_course_1": "UXD",
            "day": "Wednesday",
            "Column12": "4-5pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh"
        },
        {
            "course": "INF2169H",
            "semester": "S",
            "title": "User-Centred Information Systems Development",
            "sessionType": "TUT",
            "section": 106,
            "credit": 0,
            "required_course_1": "UXD",
            "day": "Wednesday",
            "Column12": "5:15-6:15pm",
            "method": "In-Person",
            "instructor": "Anastasia Kuzminykh"
        },
        {
            "course": "INF2171H",
            "semester": "S",
            "title": "Usability Assessment: Concepts, Methods and Tools",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Thursday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2171H",
            "semester": "S",
            "title": "Usability Assessment: Concepts, Methods and Tools",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2172H",
            "semester": "S",
            "title": "Reader Advisory: Reference Work and Resources",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Friday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2173H",
            "semester": "S",
            "title": "Information Professional Practicum ",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Friday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "2nd+ year MI students only"
        },
        {
            "course": "INF2273H",
            "semester": "S",
            "title": "Information Professional Practicum II",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Friday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "2nd+ year MI students only who have completed INF2173H"
        },
        {
            "course": "INF2175H",
            "semester": "S",
            "title": "Managing Organizational Records I",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": "KMIM",
            "day": "Tuesday ",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2177H ",
            "semester": "S",
            "title": "Information Management and Systems",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ISD",
            "day": "Monday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Safwat Hassan",
            "Column17": "recommended to be taken in 2nd year"
        },
        {
            "course": "INF2179H",
            "semester": "S",
            "title": "Machine Learning with Applications in Python",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2178H",
            "semester": "S",
            "title": "Experimental Design for Data Science",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "HCDS",
            "day": "Monday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Shion Guha"
        },
        {
            "course": "INF2181H",
            "semester": "S",
            "title": "Information, Policy, Regulation, and Law",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "CIPS",
            "day": "Tuesday ",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Victoria Owen"
        },
        {
            "course": "INF2184H",
            "semester": "S",
            "title": "Appraisal for Records Retention and Archives Acquisition",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "day": "Tuesday ",
            "Column12": "4-6pm",
            "method": "In-Person",
            "instructor": "Fiorella Foscarini"
        },
        {
            "course": "INF2184H",
            "semester": "S",
            "title": "Appraisal for Records Retention and Archives Acquisition",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "ARM",
            "day": "Wednesday",
            "Column12": "1-3pm",
            "method": "In-Person",
            "instructor": "Fiorella Foscarini"
        },
        {
            "course": "INF2185H",
            "semester": "S",
            "title": "Libraries, Archives, Museums: Intersections and Tensions",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "4-6pm",
            "method": "In-Person",
            "instructor": "Heather MacNeil",
            "Column17": "for full-time students: successful completion of year 1 of either: the Combined Degree Program (CDP), or the MMSt or MI program. For part-time students: successful completion of 4 F.C.E.s in the CDP, or the MMSt or MI program."
        },
        {
            "course": "INF2186H",
            "semester": "S",
            "title": "Metadata Schemas and Applications",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": "KMIM",
            "day": "Thursday",
            "Column12": "6:30-8:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2186H",
            "semester": "S",
            "title": "Metadata Schemas and Applications",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "ARM",
            "required_course_2": "KMIM",
            "day": "Friday",
            "Column12": "6:30-8:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2191H",
            "semester": "S",
            "title": "User Interface Design",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "UXD",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Velian Pandeliev"
        },
        {
            "course": "INF2191H",
            "semester": "S",
            "title": "User Interface Design",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "UXD",
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Velian Pandeliev"
        },
        {
            "course": "INF2191H",
            "semester": "S",
            "title": "User Interface Design",
            "sessionType": "LEC",
            "section": 103,
            "credit": 0.5,
            "required_course_1": "UXD",
            "day": "Friday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Velian Pandeliev"
        },
        {
            "course": "INF2192H",
            "semester": "S",
            "title": "Representing UX",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "UXD",
            "day": "Tuesday ",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Priyank Chandra",
            "Column17": "2nd+ year MI students only"
        },
        {
            "course": "INF2192H",
            "semester": "S",
            "title": "Representing UX",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "UXD",
            "day": "Tuesday ",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Priyank Chandra",
            "Column17": "2nd+ year MI students only"
        },
        {
            "course": "INF2200H",
            "semester": "S",
            "title": "UX Leadership and Influence",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD",
            "instructor_two": "TBD"
        },
        {
            "course": "INF2202H",
            "semester": "S",
            "title": "Data Governance in the World of Big Data",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2205H",
            "semester": "S",
            "title": "Designing Sustainable & Resilient Machine Learning Systems with MLOps",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Friday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2210H",
            "semester": "S",
            "title": "Human Values in Data Science",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "HCDS",
            "day": "Tuesday ",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Tegan Maharaj",
            "Column17": "2nd+ year MI students only"
        },
        {
            "course": "INF2210H",
            "semester": "S",
            "title": "Human Values in Data Science",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "HCDS",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Seamus Ross",
            "Column17": "2nd+ year MI students only"
        },
        {
            "course": "INF2224H",
            "semester": "S",
            "title": "Service Design",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Tuesday ",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2225H",
            "semester": "S",
            "title": "Digital Discourse",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Friday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Patrick Keilty"
        },
        {
            "course": "INF2234H",
            "semester": "S",
            "title": "Academic Librarianship",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2235H",
            "semester": "S",
            "title": "Outer Space and the City",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Marie Pier Boucher"
        },
        {
            "course": "INF2239H",
            "semester": "S",
            "title": "Information, Misinformation & Health",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Colin Furness"
        },
        {
            "course": "INF2242H",
            "semester": "S",
            "title": "Studying Information and Knowledge Practices",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "CIPS",
            "day": "Friday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Negin Dahya"
        },
        {
            "course": "INF2243H",
            "semester": "S",
            "title": "Critical Histories of Information and Communication Technologies",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "CIPS",
            "required_course_2": "C&T",
            "day": "Monday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Alan Galey"
        },
        {
            "course": "INF2245H",
            "semester": "S",
            "title": "Platforms: Global Histories, Practices, and Theories",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Julie Chen"
        },
        {
            "course": "INF2250H",
            "semester": "S",
            "title": "Copyright for Information Professionals",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2256H",
            "semester": "S",
            "title": "Digital Scholarship",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Tuesday ",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Christopher Young"
        },
        {
            "course": "INF2311H",
            "semester": "S",
            "title": "Managing AudioVisual Material",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Tuesday ",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "Rachel Beattie"
        },
        {
            "course": "INF2313H",
            "semester": "S",
            "title": "Service Science",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "INF2320H",
            "semester": "S",
            "title": "Remix Culture",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "C&T",
            "day": "Thursday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Sara Grimes"
        },
        {
            "course": "INF2330H",
            "semester": "S",
            "title": "Information Ethnography",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Jenna Hartel"
        },
        {
            "course": "INF2331H",
            "semester": "S",
            "title": "The Future of the Book",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "C&T",
            "day": "Wednesday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Alan Galey"
        },
        {
            "course": "INF2403H",
            "semester": "S",
            "title": "Special Topics in Information",
            "subtitle": "Digital Archives Workflows",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Thursday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "2nd+ year MI students only"
        },
        {
            "course": "INF2406H",
            "semester": "S",
            "title": "Special Topics in Information",
            "subtitle": "Special Topics in Information: Issues in Health Data Science and AI",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "10-12pm",
            "method": "In-Person",
            "instructor": "Aviv Shachak"
        },
        {
            "course": "INF3010H",
            "semester": "S",
            "title": "Power, Media, and Technology",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Tuesday ",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Alessandro Delfanti",
            "Column17": "PhD students only"
        },
        {
            "course": "INF3012H",
            "semester": "S",
            "title": "Social Scientific Methods for Media",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Thursday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Jeff Boase",
            "Column17": "PhD students only"
        },
        {
            "course": "INF3XXXH",
            "semester": "S",
            "title": "Applied Statistics",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Rohan Alexander",
            "Column17": "PhD students only, course is in development and is research methods related to stats, needs approval"
        },
        {
            "course": "KMD1002H",
            "semester": "S",
            "title": "Applications in Knowledge Media",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "KMD collaborative specialization",
            "day": "Tuesday ",
            "Column12": "4-6pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "KMD CS students have priority"
        },
        {
            "course": "MSL1150H",
            "semester": "S",
            "title": "Collection Management",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "MMSt",
            "day": "Tuesday ",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Cara Krmpotich"
        },
        {
            "course": "MSL1150H",
            "semester": "S",
            "title": "Collection Management",
            "sessionType": "LEC",
            "section": 102,
            "credit": 0.5,
            "required_course_1": "MMSt",
            "day": "Tuesday ",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Cara Krmpotich"
        },
        {
            "course": "MSL1230H",
            "semester": "S",
            "title": "Ethics, Leadership, and Management",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "required_course_1": "MMSt",
            "day": "Wednesday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "MSL1350H",
            "semester": "S",
            "title": "Museum and Their Public",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "2nd+ year MMSt students"
        },
        {
            "course": "MSL2050H",
            "semester": "S",
            "title": "Curating Science",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Thursdays",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "MSL2100H",
            "semester": "S",
            "title": "Museum Environment ",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Friday",
            "Column12": "9-5pm",
            "method": "In-Person",
            "instructor": "TBD",
            "Column17": "intensive, 6 weeks, 9-5pm on Fridays"
        },
        {
            "course": "MSL2230H",
            "semester": "S",
            "title": "Nature & Culture: Histories of Heritage Interpretation in North America",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Thursday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "MSL2326H",
            "semester": "S",
            "title": "Artifact, Audience, and Text: Writing in the Museum",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "6:30-9:30pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "MSL2335H",
            "semester": "S",
            "title": "The Digital Museum: From Strategy to Implementation",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Monday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "TBD"
        },
        {
            "course": "MSL2340H",
            "semester": "S",
            "title": "Issues in Cultural Policy and Contemporary Culture",
            "sessionType": "LEC",
            "section": 101,
            "credit": 0.5,
            "day": "Wednesday",
            "Column12": "1-4pm",
            "method": "In-Person",
            "instructor": "Alan Stanbridge"
        },
        {
            "course": "MSL4000Y",
            "semester": "Y",
            "title": "Museum Studies Capstone Projects",
            "sessionType": "LEC",
            "section": 101,
            "credit": 1,
            "required_course_1": "MMSt",
            "day": "Thursday",
            "Column12": "9-12pm",
            "method": "In-Person",
            "instructor": "Cara Krmpotich",
            "instructor_two": "Morgan Mavis",
            "Column17": "2nd+ year MMSt students only"
        }

]